const html = (value) => String(value ?? "")
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;");

const stateClass = (value) => `is-${String(value).toLowerCase().replace(/[^a-z0-9]+/g, "-")}`;

function nav(prefix) {
  return `
    <button type="button" data-nav="workflows" onclick="this.closest('[data-view]').dataset.view='workflows'">Workflows</button>
    <button type="button" data-nav="agents" onclick="this.closest('[data-view]').dataset.view='agents'">Agents</button>
    <button type="button" data-nav="runs" onclick="this.closest('[data-view]').dataset.view='runs'">Runs</button>
    <button type="button" data-nav="spend" onclick="this.closest('[data-view]').dataset.view='spend'">Spend</button>
    <button type="button" class="${prefix}-create" data-nav="create" onclick="this.closest('[data-view]').dataset.view='create'">Create workflow</button>`;
}

function createFlow(c, prefix) {
  return `
    <section class="${prefix}-createflow" data-create>
      <ol class="${prefix}-steps" aria-label="Workflow creation steps">
        ${c.creation.steps.map((step, index) => `<li class="${index === 0 ? "current" : ""}"><span>${String(index + 1).padStart(2, "0")}</span>${html(step)}</li>`).join("")}
      </ol>
      <div class="${prefix}-goal">
        <p class="${prefix}-eyebrow">Step 1 · Goal</p>
        <h2>What should happen, and where must it stop?</h2>
        <label>Workflow goal
          <textarea rows="5">${html(c.creation.rawGoal)}</textarea>
        </label>
        <details open>
          <summary>Enhanced goal review <span>Ready to apply</span></summary>
          <p data-enhanced>${html(c.creation.enhancedGoal)}</p>
          <button type="button" onclick="const box=this.closest('[data-create]');box.querySelector('textarea').value=box.querySelector('[data-enhanced]').textContent.trim();this.textContent='Enhanced goal applied';this.setAttribute('aria-pressed','true')">Use enhanced goal</button>
        </details>
      </div>
      <aside class="${prefix}-activation">
        <p class="${prefix}-eyebrow">Activation gate</p>
        <h3>Test before listening</h3>
        <p>${html(c.creation.test)}</p>
        <label class="${prefix}-check"><input type="checkbox" onchange="this.closest('[data-create]').querySelector('[data-activate]').disabled=!this.checked"> Fixture PR connected and test passed</label>
        <button type="button" data-activate disabled onclick="this.textContent='Workflow activated';this.disabled=true">Activate workflow</button>
        <small>Activation stays unavailable until the configured trigger, authority, limits, and fixture test pass.</small>
      </aside>
    </section>`;
}

function renderAnth1(c) {
  const workflowRows = c.workflows.map((w, index) => `
    <button type="button" class="a1-workflow ${index === 0 ? "selected" : ""}" aria-pressed="${index === 0}">
      <span class="a1-wf-line"><strong>${html(w.name)}</strong><i class="${stateClass(w.lifecycle)}">${html(w.lifecycle)}</i></span>
      <span>${html(w.trigger)}</span>
      <span class="a1-wf-meta"><b>${w.active ? `${w.active} active run` : "No active run"}</b><em>${html(w.budget)}</em></span>
    </button>`).join("");
  const topology = c.workflows[0].topology.map((node, index) => `
    <div class="a1-node ${index === 2 ? "current" : ""}">
      <span>${index === 0 ? "TRIGGER" : index === c.workflows[0].topology.length - 1 ? "OUTCOME" : "AGENT"}</span>
      <strong>${html(node)}</strong>
      <small>${index === 2 ? "Executing · 08m 42s" : index < 2 ? "Complete" : "Awaiting verification"}</small>
    </div>${index < c.workflows[0].topology.length - 1 ? '<b class="a1-edge" aria-hidden="true">→</b>' : ""}`).join("");
  return `
  <article class="a1" data-view="workflows">
    <style>
      .a1{--paper:#f3f6f7;--panel:#fff;--ink:#172126;--muted:#617078;--line:#c8d2d6;--accent:#075d68;--accent2:#d97941;--ok:#26754d;--warn:#9a3f32;background:var(--paper);color:var(--ink);font:13px/1.45 "Avenir Next",Avenir,Arial,sans-serif;height:100vh;min-height:640px;display:grid;grid-template-rows:62px minmax(0,1fr);overflow:hidden;color-scheme:light}
      @media(prefers-color-scheme:dark){.a1{--paper:#11191c;--panel:#172226;--ink:#edf2f2;--muted:#9eafb3;--line:#34464b;--accent:#62c1c9;--accent2:#eea16d;--ok:#76c796;--warn:#f09283;color-scheme:dark}}
      html[data-theme="light"] .a1{--paper:#f3f6f7;--panel:#fff;--ink:#172126;--muted:#617078;--line:#c8d2d6;--accent:#075d68;--accent2:#d97941;--ok:#26754d;--warn:#9a3f32;color-scheme:light}
      html[data-theme="dark"] .a1{--paper:#11191c;--panel:#172226;--ink:#edf2f2;--muted:#9eafb3;--line:#34464b;--accent:#62c1c9;--accent2:#eea16d;--ok:#76c796;--warn:#f09283;color-scheme:dark}
      .a1 *{box-sizing:border-box}.a1 button,.a1 textarea{font:inherit;color:inherit}.a1 button{cursor:pointer}.a1 button:focus-visible,.a1 textarea:focus-visible,.a1 summary:focus-visible{outline:3px solid var(--accent2);outline-offset:2px}.a1-top{display:grid;grid-template-columns:210px auto 1fr auto;align-items:center;border-bottom:1px solid var(--line);background:var(--panel)}
      .a1-brand{height:100%;display:flex;align-items:center;gap:10px;padding:0 18px;border-right:1px solid var(--line);font:700 18px/1 "Iowan Old Style",Georgia,serif;letter-spacing:-.02em}.a1-brand mark{width:15px;height:27px;background:var(--accent);border-radius:9px 2px;color:transparent;transform:rotate(24deg)}
      .a1-nav{display:flex;height:100%}.a1-nav button{border:0;border-right:1px solid var(--line);background:transparent;padding:0 15px;font-weight:650}.a1-nav button:hover{background:var(--paper)}.a1[data-view="workflows"] [data-nav="workflows"],.a1[data-view="agents"] [data-nav="agents"],.a1[data-view="runs"] [data-nav="runs"],.a1[data-view="spend"] [data-nav="spend"],.a1[data-view="create"] [data-nav="create"]{box-shadow:inset 0 -4px var(--accent);color:var(--accent)}
      .a1-nav .a1-create{background:var(--accent);color:var(--panel);box-shadow:none}.a1-notice{justify-self:end;color:var(--muted);font:11px/1.2 "SFMono-Regular",Consolas,monospace;padding:0 16px}.a1-theme{margin-right:14px;border:1px solid var(--line);background:var(--panel);border-radius:99px;padding:7px 11px}
      .a1-main{min-height:0;overflow:auto}.a1-view{display:none;height:100%;min-height:560px}.a1[data-view="workflows"] .a1-v-workflows,.a1[data-view="agents"] .a1-v-agents,.a1[data-view="runs"] .a1-v-runs,.a1[data-view="spend"] .a1-v-spend,.a1[data-view="create"] .a1-v-create{display:grid}
      .a1-v-workflows{grid-template-columns:310px minmax(480px,1fr) 310px}.a1-roster{border-right:1px solid var(--line);background:var(--panel);overflow:auto}.a1-sectionhead{padding:22px 18px 14px;border-bottom:1px solid var(--line)}.a1-eyebrow{text-transform:uppercase;letter-spacing:.13em;font:700 10px/1.2 "SFMono-Regular",Consolas,monospace;color:var(--accent);margin:0 0 7px}.a1-sectionhead h1,.a1-canvas h2,.a1-goal h2{font:600 26px/1.05 "Iowan Old Style",Georgia,serif;letter-spacing:-.03em;margin:0}.a1-count{color:var(--muted);margin:6px 0 0}
      .a1-workflow{display:block;width:100%;padding:18px;text-align:left;border:0;border-bottom:1px solid var(--line);background:transparent}.a1-workflow.selected{background:var(--paper);box-shadow:inset 4px 0 var(--accent)}.a1-wf-line,.a1-wf-meta{display:flex;align-items:center;justify-content:space-between;gap:10px}.a1-wf-line strong{font-size:15px}.a1-wf-line i,.a1-chip{font:700 10px/1 "SFMono-Regular",Consolas,monospace;text-transform:uppercase;letter-spacing:.07em;border:1px solid currentColor;border-radius:99px;padding:5px 7px;font-style:normal}.a1-workflow>span:nth-child(2){display:block;color:var(--muted);margin:8px 0 16px}.a1-wf-meta{font-size:11px}.a1-wf-meta b{color:var(--accent)}.a1-wf-meta em{font-style:normal;color:var(--muted)}.a1 .is-active,.a1 .is-listening{color:var(--ok)}.a1 .is-draft{color:var(--muted)}
      .a1-canvas{padding:28px;display:flex;flex-direction:column;min-width:0}.a1-canvashead{display:flex;justify-content:space-between;gap:20px;align-items:start}.a1-canvashead p{margin:7px 0;color:var(--muted)}.a1-runselect{border:1px solid var(--line);background:var(--panel);padding:9px 11px}.a1-graph{display:flex;align-items:center;justify-content:center;flex:1;min-height:250px;overflow:auto;padding:30px 0}.a1-node{min-width:130px;border:1px solid var(--line);background:var(--panel);padding:13px;position:relative}.a1-node span{display:block;color:var(--muted);font:700 9px/1 monospace;letter-spacing:.12em}.a1-node strong{display:block;margin:10px 0 5px}.a1-node small{color:var(--muted)}.a1-node.current{border:2px solid var(--accent);box-shadow:6px 6px 0 color-mix(in srgb,var(--accent) 18%,transparent)}.a1-node.current:before{content:"LIVE";position:absolute;right:7px;top:7px;color:var(--accent);font:800 9px monospace}.a1-edge{color:var(--accent);font-size:20px;padding:0 7px}
      .a1-truthbar{display:grid;grid-template-columns:repeat(4,1fr);border:1px solid var(--line);background:var(--panel)}.a1-truthbar div{padding:13px;border-right:1px solid var(--line)}.a1-truthbar div:last-child{border:0}.a1-truthbar span{display:block;color:var(--muted);font-size:10px}.a1-truthbar strong{display:block;margin-top:5px}.a1-inspector{background:var(--panel);border-left:1px solid var(--line);overflow:auto}.a1-inspector>header{padding:22px 18px;border-bottom:1px solid var(--line)}.a1-inspector h3{margin:3px 0;font-size:16px}.a1-inspector header p{color:var(--muted);margin:5px 0 0}.a1-child{padding:15px 18px;border-bottom:1px solid var(--line);display:grid;grid-template-columns:10px 1fr;gap:10px}.a1-child:before{content:"";width:8px;height:8px;border-radius:50%;background:var(--ok);margin-top:5px}.a1-child:last-of-type:before{background:var(--accent2)}.a1-child strong,.a1-child span{display:block}.a1-child span{color:var(--muted);font-size:11px}.a1-fact{display:grid;grid-template-columns:1fr 1fr;gap:12px;padding:16px 18px}.a1-fact div{border-top:1px solid var(--line);padding-top:9px}.a1-fact span{display:block;color:var(--muted);font-size:10px}.a1-fact b{display:block;margin-top:4px}
      .a1-v-agents,.a1-v-runs,.a1-v-spend,.a1-v-create{padding:28px;align-content:start;gap:22px}.a1-title{display:flex;justify-content:space-between;align-items:end;border-bottom:1px solid var(--line);padding-bottom:16px}.a1-title h1{font:600 34px/1 "Iowan Old Style",Georgia,serif;margin:0}.a1-title p{color:var(--muted);margin:0}.a1-table{width:100%;border-collapse:collapse;background:var(--panel)}.a1-table th{text-align:left;color:var(--muted);font:700 10px monospace;letter-spacing:.1em;text-transform:uppercase;padding:11px;border:1px solid var(--line)}.a1-table td{padding:15px 11px;border:1px solid var(--line);vertical-align:top}.a1-table td strong,.a1-table td span{display:block}.a1-table td span{color:var(--muted);font-size:11px;margin-top:4px}.a1-availability{color:var(--accent)}
      .a1-runlayout,.a1-spendlayout{display:grid;grid-template-columns:minmax(0,1.3fr) minmax(280px,.7fr);gap:20px}.a1-live,.a1-spendcard{background:var(--panel);border:1px solid var(--line);padding:20px}.a1-live h2,.a1-spendcard h2{margin:2px 0 16px}.a1-livegrid{display:grid;grid-template-columns:repeat(4,1fr);gap:1px;background:var(--line);border:1px solid var(--line)}.a1-livegrid div{background:var(--panel);padding:12px}.a1-livegrid span{display:block;color:var(--muted);font-size:10px}.a1-scope{display:flex;align-items:center;justify-content:space-between;border-top:1px solid var(--line);padding:12px 0}.a1-scope b{font:11px monospace;color:var(--accent)}.a1-truth{border:1px solid var(--line);padding:15px;margin-top:10px}.a1-truth strong,.a1-truth span{display:block}.a1-truth span{color:var(--muted);margin-top:5px}
      .a1-createflow{display:grid;grid-template-columns:190px minmax(400px,1fr) 280px;gap:0;background:var(--panel);border:1px solid var(--line);min-height:480px}.a1-steps{list-style:none;margin:0;padding:0;border-right:1px solid var(--line)}.a1-steps li{padding:13px 14px;border-bottom:1px solid var(--line);color:var(--muted)}.a1-steps li span{font:10px monospace;margin-right:10px}.a1-steps li.current{color:var(--accent);font-weight:700;box-shadow:inset 4px 0 var(--accent)}.a1-goal{padding:28px}.a1-goal label{display:block;font-weight:700;margin-top:24px}.a1-goal textarea{display:block;width:100%;resize:vertical;background:var(--paper);border:1px solid var(--line);padding:13px;margin-top:7px}.a1-goal details{border:1px solid var(--line);margin-top:18px}.a1-goal summary{padding:12px;font-weight:700;cursor:pointer}.a1-goal summary span{float:right;color:var(--ok);font-size:11px}.a1-goal details p{padding:0 14px;color:var(--muted)}.a1-goal details button,.a1-activation button{margin:0 14px 14px;border:0;background:var(--accent);color:var(--panel);padding:10px 13px;font-weight:700}.a1-activation{border-left:1px solid var(--line);padding:28px;background:var(--paper)}.a1-activation h3{font:600 22px "Iowan Old Style",Georgia,serif;margin:4px 0}.a1-check{display:block;border:1px solid var(--line);background:var(--panel);padding:12px;margin:24px 0 12px}.a1-activation button{margin:0;width:100%}.a1-activation button:disabled{opacity:.4;cursor:not-allowed}.a1-activation small{display:block;color:var(--muted);margin-top:12px}
      @media(max-width:900px){.a1{height:auto;min-height:100vh;overflow:visible}.a1-top{grid-template-columns:1fr auto}.a1-nav{grid-column:1/-1;grid-row:2;overflow:auto;border-top:1px solid var(--line)}.a1-top{height:auto}.a1-brand{min-height:58px}.a1-notice{display:none}.a1-v-workflows{grid-template-columns:1fr}.a1-roster,.a1-inspector{border:0}.a1-canvas{min-height:520px}.a1-inspector{border-top:1px solid var(--line)}.a1-createflow{grid-template-columns:1fr}.a1-steps{display:flex;overflow:auto;border-right:0}.a1-steps li{white-space:nowrap}.a1-activation{border-left:0;border-top:1px solid var(--line)}.a1-runlayout,.a1-spendlayout{grid-template-columns:1fr}}
      @media(prefers-reduced-motion:reduce){.a1 *{scroll-behavior:auto!important;transition:none!important}}
    </style>
    <header class="a1-top">
      <div class="a1-brand"><mark>B</mark>Bitterblossom</div>
      <nav class="a1-nav" aria-label="Primary">${nav("a1")}</nav>
      <p class="a1-notice">${html(c.notice)}</p>
      <button type="button" class="a1-theme" data-theme-toggle aria-label="Toggle light and dark theme">◐ Theme</button>
    </header>
    <main class="a1-main">
      <section class="a1-view a1-v-workflows">
        <aside class="a1-roster"><div class="a1-sectionhead"><p class="a1-eyebrow">Configured roster</p><h1>Workflows</h1><p class="a1-count">${c.workflows.length} definitions · one currently active</p></div>${workflowRows}</aside>
        <section class="a1-canvas">
          <header class="a1-canvashead"><div><p class="a1-eyebrow">Active configuration</p><h2>${html(c.workflows[0].name)}</h2><p>${html(c.workflows[0].trigger)}</p></div><button class="a1-runselect" type="button">Overlay · ${html(c.run.id)} ▾</button></header>
          <div class="a1-graph" aria-label="PR Review topology">${topology}</div>
          <div class="a1-truthbar"><div><span>Workflow state</span><strong>Active</strong></div><div><span>Trigger health</span><strong class="is-listening">Listening</strong></div><div><span>Run lifecycle</span><strong>Executing</strong></div><div><span>Domain result</span><strong>Pending</strong></div></div>
        </section>
        <aside class="a1-inspector"><header><p class="a1-eyebrow">Selected run overlay</p><h3>${html(c.run.id)}</h3><p>${html(c.run.trigger)} · ${html(c.run.elapsed)}</p></header>${c.run.children.map(child => `<div class="a1-child"><div><strong>${html(child.name)}</strong><span>${html(child.state)} · ${html(child.result)}</span></div></div>`).join("")}<div class="a1-fact"><div><span>Authority</span><b>${html(c.run.budget)}</b></div><div><span>Cost</span><b>${html(c.run.cost)}</b></div><div><span>Verification</span><b>In progress</b></div><div><span>Parent</span><b>${html(c.run.parent)}</b></div></div></aside>
      </section>
      <section class="a1-view a1-v-agents"><header class="a1-title"><div><p class="a1-eyebrow">Roster definitions</p><h1>Agents</h1></div><p>Assignment is separate from availability.</p></header><table class="a1-table"><thead><tr><th>Agent</th><th>Availability</th><th>Runtime</th><th>Authority ceiling</th><th>Workflow use</th><th>Now</th></tr></thead><tbody>${c.agents.map(a => `<tr><td><strong>${html(a.name)}</strong></td><td class="a1-availability">${html(a.availability)}</td><td><strong>${html(a.model)}</strong><span>${html(a.harness)}</span></td><td>${html(a.ceiling)}</td><td>${html(a.workflows)}</td><td>${a.active ? `${a.active} active` : "Idle"}</td></tr>`).join("")}</tbody></table></section>
      <section class="a1-view a1-v-runs"><header class="a1-title"><div><p class="a1-eyebrow">Evidence ledger</p><h1>Runs</h1></div><p>Execution, result, and proof remain separate.</p></header><div class="a1-runlayout"><div class="a1-live"><p class="a1-eyebrow">Live now</p><h2>${html(c.run.id)}</h2><div class="a1-livegrid"><div><span>Lifecycle</span><strong>${html(c.run.state)}</strong></div><div><span>Current step</span><strong>${html(c.run.step)}</strong></div><div><span>Elapsed</span><strong>${html(c.run.elapsed)}</strong></div><div><span>Cost</span><strong>${html(c.run.cost)}</strong></div></div></div><div class="a1-live"><p class="a1-eyebrow">Evidence attached</p>${c.run.children.map(x => `<div class="a1-scope"><span>${html(x.name)}</span><b>${html(x.result)}</b></div>`).join("")}</div></div><table class="a1-table"><thead><tr><th>Workflow / ref</th><th>Execution</th><th>Domain result</th><th>Verification</th><th>Cost</th></tr></thead><tbody>${c.recentRuns.map(r => `<tr><td><strong>${html(r.workflow)}</strong><span>${html(r.ref)}</span></td><td>${html(r.execution)}</td><td>${html(r.domain)}</td><td>${html(r.verification)}</td><td>${html(r.cost)}</td></tr>`).join("")}</tbody></table></section>
      <section class="a1-view a1-v-spend"><header class="a1-title"><div><p class="a1-eyebrow">Authority and accounting</p><h1>Spend</h1></div><p>Unavailable is a coverage gap, never zero.</p></header><div class="a1-spendlayout"><div class="a1-spendcard"><p class="a1-eyebrow">Control hierarchy</p><h2>Admission limits</h2>${c.spend.scopes.map((s,i) => `<div class="a1-scope"><span>${html(s)}</span><b>${i===0?"ENFORCED":i===2?"CONFIGURED":"INHERITED"}</b></div>`).join("")}</div><div class="a1-spendcard"><p class="a1-eyebrow">Cost truth</p><h2>Three reporting states</h2>${c.spend.truth.map(t => `<div class="a1-truth"><strong>${html(t.label)} · ${html(t.value)}</strong><span>${html(t.state)}</span></div>`).join("")}</div></div></section>
      <section class="a1-view a1-v-create">${createFlow(c,"a1")}</section>
    </main>
  </article>`;
}

function renderAnth2(c) {
  const routes = c.workflows.map((w, wi) => `
    <section class="a2-route ${wi === 0 ? "selected" : ""}">
      <header><div><span>${wi === 0 ? "LIVE DEFINITION" : "DRAFT DEFINITION"}</span><h2>${html(w.name)}</h2></div><p>${html(w.trigger)}</p><b>${w.active ? `${w.active} active` : "No active run"}</b></header>
      <div class="a2-track">${w.topology.map((node, ni) => `<div class="a2-stop ${wi === 0 && ni === 2 ? "running" : ""}"><i>${ni === 0 ? "event" : ni === w.topology.length - 1 ? "close" : "agent"}</i><strong>${html(node)}</strong><small>${wi === 0 && ni === 2 ? "Executing" : wi === 0 && ni < 2 ? "Passed" : wi === 0 ? "Waiting" : "Not run"}</small></div>`).join("")}</div>
      <footer><span>Workflow <b>${html(w.lifecycle)}</b></span><span>Trigger <b>${wi === 0 ? "Listening" : "Not listening"}</b></span><span>Latest execution <b>${html(w.latestExecution)}</b></span><span>Domain <b>${html(w.latestDomain)}</b></span><span>Verification <b>${html(w.verification)}</b></span><span>Cost <b>${html(w.cost)}</b></span></footer>
    </section>`).join("");
  return `
  <article class="a2" data-view="workflows">
    <style>
      .a2{--field:#e9eef0;--surface:#f8faf9;--ink:#15262d;--muted:#60757d;--line:#aebdc2;--route:#bc4f3b;--signal:#12636d;--lime:#accc74;--deep:#263c47;background:var(--field);color:var(--ink);font:13px/1.4 "Gill Sans","Avenir Next",sans-serif;height:100vh;min-height:640px;display:grid;grid-template-columns:118px minmax(0,1fr);overflow:hidden;color-scheme:light}
      @media(prefers-color-scheme:dark){.a2{--field:#142126;--surface:#1d2d33;--ink:#edf4f2;--muted:#9bb0b6;--line:#40555c;--route:#ed8069;--signal:#69c2c9;--lime:#bddc86;--deep:#d6e3e6;color-scheme:dark}}
      html[data-theme="light"] .a2{--field:#e9eef0;--surface:#f8faf9;--ink:#15262d;--muted:#60757d;--line:#aebdc2;--route:#bc4f3b;--signal:#12636d;--lime:#accc74;--deep:#263c47;color-scheme:light}html[data-theme="dark"] .a2{--field:#142126;--surface:#1d2d33;--ink:#edf4f2;--muted:#9bb0b6;--line:#40555c;--route:#ed8069;--signal:#69c2c9;--lime:#bddc86;--deep:#d6e3e6;color-scheme:dark}
      .a2 *{box-sizing:border-box}.a2 button,.a2 textarea{font:inherit;color:inherit}.a2 button{cursor:pointer}.a2 button:focus-visible,.a2 textarea:focus-visible,.a2 summary:focus-visible{outline:3px solid var(--lime);outline-offset:2px}.a2-rail{background:var(--deep);color:var(--field);display:flex;flex-direction:column;min-height:0}.a2-mark{height:100px;display:grid;place-items:center;border-bottom:1px solid color-mix(in srgb,var(--field) 25%,transparent);font:700 27px/1 "Arial Narrow",sans-serif;letter-spacing:-.08em}.a2-mark span{display:block;transform:rotate(-8deg)}.a2-nav{display:flex;flex-direction:column}.a2-nav button{height:62px;background:transparent;color:inherit;border:0;border-bottom:1px solid color-mix(in srgb,var(--field) 25%,transparent);font:700 11px/1 "Arial Narrow",sans-serif;letter-spacing:.05em;text-transform:uppercase}.a2-nav button:hover{background:color-mix(in srgb,var(--field) 10%,transparent)}.a2-nav .a2-create{height:82px;background:var(--route);color:#fff}.a2[data-view="workflows"] [data-nav="workflows"],.a2[data-view="agents"] [data-nav="agents"],.a2[data-view="runs"] [data-nav="runs"],.a2[data-view="spend"] [data-nav="spend"],.a2[data-view="create"] [data-nav="create"]{box-shadow:inset 6px 0 var(--lime)}.a2-theme{margin:auto 14px 16px;border:1px solid currentColor;background:transparent;color:inherit;padding:9px 4px}
      .a2-shell{min-width:0;display:grid;grid-template-rows:72px minmax(0,1fr)}.a2-head{display:flex;align-items:center;gap:18px;padding:0 24px;background:var(--surface);border-bottom:1px solid var(--line)}.a2-head h1{font:700 24px/1 "Arial Narrow","Avenir Next Condensed",sans-serif;letter-spacing:.02em;margin:0;text-transform:uppercase}.a2-head p{margin-left:auto;color:var(--muted);font:10px/1.2 "SFMono-Regular",monospace}.a2-pulse{width:9px;height:9px;border-radius:50%;background:var(--lime);box-shadow:0 0 0 4px color-mix(in srgb,var(--lime) 25%,transparent)}
      .a2-content{overflow:auto;min-height:0}.a2-view{display:none;min-height:100%;padding:24px}.a2[data-view="workflows"] .a2-v-workflows,.a2[data-view="agents"] .a2-v-agents,.a2[data-view="runs"] .a2-v-runs,.a2[data-view="spend"] .a2-v-spend,.a2[data-view="create"] .a2-v-create{display:block}.a2-title{display:flex;align-items:end;gap:20px;margin-bottom:18px}.a2-kicker{font:700 10px/1 monospace;letter-spacing:.15em;text-transform:uppercase;color:var(--route);margin:0 0 5px}.a2-title h2{font:700 33px/.95 "Arial Narrow","Avenir Next Condensed",sans-serif;text-transform:uppercase;letter-spacing:-.02em;margin:0}.a2-title>p:last-child{color:var(--muted);margin:0 0 2px auto}
      .a2-route{background:var(--surface);border:1px solid var(--line);margin-bottom:16px}.a2-route.selected{border-top:5px solid var(--route)}.a2-route>header{display:grid;grid-template-columns:240px 1fr auto;gap:20px;align-items:center;padding:14px 18px;border-bottom:1px solid var(--line)}.a2-route header span{font:700 9px monospace;letter-spacing:.12em;color:var(--route)}.a2-route h2{margin:3px 0 0;font:700 20px "Arial Narrow",sans-serif;text-transform:uppercase}.a2-route header p{color:var(--muted);margin:0}.a2-route header>b{font:700 10px monospace;text-transform:uppercase;color:var(--signal);border:1px solid currentColor;padding:6px 8px}.a2-track{display:grid;grid-template-columns:repeat(4,1fr);padding:26px 30px;position:relative}.a2-track:before{content:"";position:absolute;left:10%;right:10%;top:46px;height:6px;background:var(--route)}.a2-route:not(.selected) .a2-track:before{background:var(--line)}.a2-stop{position:relative;text-align:center;z-index:1}.a2-stop:before{content:"";display:block;width:28px;height:28px;background:var(--surface);border:7px solid var(--route);border-radius:50%;margin:5px auto 9px}.a2-route:not(.selected) .a2-stop:before{border-color:var(--line)}.a2-stop.running:before{background:var(--lime);border-color:var(--signal)}.a2-stop i{position:absolute;top:-8px;left:50%;transform:translateX(-50%);font:700 8px monospace;color:var(--muted);font-style:normal;text-transform:uppercase}.a2-stop strong,.a2-stop small{display:block}.a2-stop small{color:var(--muted);margin-top:3px}.a2-route>footer{display:grid;grid-template-columns:repeat(6,1fr);border-top:1px solid var(--line)}.a2-route footer span{padding:9px 12px;color:var(--muted);font-size:10px;border-right:1px solid var(--line)}.a2-route footer span:last-child{border:0}.a2-route footer b{display:block;color:var(--ink);font-size:11px;margin-top:4px}
      .a2-overlay{display:grid;grid-template-columns:260px 1fr;background:var(--deep);color:var(--field);margin-top:8px}.a2-overlay>header{padding:20px;border-right:1px solid color-mix(in srgb,var(--field) 25%,transparent)}.a2-overlay h3{font:700 18px "Arial Narrow",sans-serif;text-transform:uppercase;margin:4px 0}.a2-overlay header p{color:color-mix(in srgb,var(--field) 70%,transparent)}.a2-overlay strong{color:var(--lime)}.a2-evidence{display:grid;grid-template-columns:repeat(3,1fr)}.a2-evidence div{padding:18px;border-right:1px solid color-mix(in srgb,var(--field) 25%,transparent)}.a2-evidence span{display:block;color:color-mix(in srgb,var(--field) 68%,transparent);font-size:10px}.a2-evidence b{display:block;margin:5px 0}.a2-evidence small{color:color-mix(in srgb,var(--field) 68%,transparent)}
      .a2-board{background:var(--surface);border:1px solid var(--line)}.a2-row{display:grid;grid-template-columns:1.1fr .8fr 1fr 1.4fr .8fr .5fr;border-bottom:1px solid var(--line);align-items:center}.a2-row:last-child{border:0}.a2-row>div{padding:14px;border-right:1px solid var(--line);min-height:62px}.a2-row>div:last-child{border:0}.a2-row.head{font:700 9px monospace;text-transform:uppercase;letter-spacing:.1em;color:var(--muted)}.a2-row strong,.a2-row span{display:block}.a2-row span{color:var(--muted);font-size:10px;margin-top:4px}.a2-tag{font:700 10px monospace;text-transform:uppercase;color:var(--signal)}
      .a2-livegrid{display:grid;grid-template-columns:1fr 1.5fr;gap:16px}.a2-panel{background:var(--surface);border:1px solid var(--line);padding:18px}.a2-panel h3{font:700 19px "Arial Narrow",sans-serif;text-transform:uppercase;margin:3px 0 15px}.a2-fact{display:flex;justify-content:space-between;gap:15px;border-top:1px solid var(--line);padding:11px 0}.a2-fact span{color:var(--muted)}.a2-coststates{display:grid;grid-template-columns:repeat(3,1fr);gap:12px}.a2-cost{border:1px solid var(--line);background:var(--surface);padding:18px;border-top:6px solid var(--signal)}.a2-cost:nth-child(2){border-top-color:var(--route)}.a2-cost:nth-child(3){border-top-color:var(--muted)}.a2-cost strong{display:block;font:700 17px "Arial Narrow",sans-serif;text-transform:uppercase}.a2-cost b{display:block;margin:18px 0 3px}.a2-cost span{color:var(--muted)}
      .a2-createflow{display:grid;grid-template-columns:170px minmax(400px,1fr) 280px;background:var(--surface);border:1px solid var(--line);min-height:500px}.a2-steps{list-style:none;margin:0;padding:0;background:var(--deep);color:var(--field)}.a2-steps li{padding:13px;border-bottom:1px solid color-mix(in srgb,var(--field) 22%,transparent);font:700 11px "Arial Narrow",sans-serif;text-transform:uppercase}.a2-steps li span{font:9px monospace;color:var(--lime);margin-right:8px}.a2-steps li.current{background:var(--route);color:#fff}.a2-goal{padding:28px}.a2-goal h2{font:700 29px/.95 "Arial Narrow",sans-serif;text-transform:uppercase;max-width:460px}.a2-goal label{display:block;font-weight:700;margin-top:20px}.a2-goal textarea{width:100%;display:block;margin-top:7px;border:1px solid var(--line);background:var(--field);padding:14px;resize:vertical}.a2-goal details{border-top:5px solid var(--signal);background:var(--field);margin-top:18px;padding:0 14px 14px}.a2-goal summary{padding:13px 0;font-weight:700;cursor:pointer}.a2-goal summary span{float:right;color:var(--signal)}.a2-goal details p{color:var(--muted)}.a2-goal details button,.a2-activation button{border:0;background:var(--signal);color:#fff;padding:10px 14px;font-weight:700}.a2-activation{padding:28px;border-left:1px solid var(--line);background:var(--field)}.a2-activation h3{font:700 22px "Arial Narrow",sans-serif;text-transform:uppercase}.a2-check{display:block;border:1px solid var(--line);background:var(--surface);padding:12px;margin:24px 0 12px}.a2-activation button{width:100%}.a2-activation button:disabled{opacity:.4}.a2-activation small{display:block;color:var(--muted);margin-top:12px}
      @media(max-width:900px){.a2{height:auto;min-height:100vh;grid-template-columns:1fr;overflow:visible}.a2-rail{position:sticky;top:0;z-index:5;display:grid;grid-template-columns:80px 1fr auto}.a2-mark{height:60px;border-bottom:0}.a2-nav{flex-direction:row;overflow:auto}.a2-nav button,.a2-nav .a2-create{height:60px;padding:0 12px;white-space:nowrap}.a2-theme{margin:11px}.a2-route>header{grid-template-columns:1fr}.a2-route>footer{grid-template-columns:repeat(3,1fr)}.a2-overlay,.a2-livegrid,.a2-createflow{grid-template-columns:1fr}.a2-overlay>header,.a2-activation{border:0;border-bottom:1px solid var(--line)}.a2-steps{display:flex;overflow:auto}.a2-steps li{white-space:nowrap}.a2-row{grid-template-columns:1fr 1fr}.a2-row.head{display:none}.a2-coststates{grid-template-columns:1fr}}
      @media(prefers-reduced-motion:reduce){.a2 *{transition:none!important}}
    </style>
    <aside class="a2-rail"><div class="a2-mark"><span>bb</span></div><nav class="a2-nav" aria-label="Primary">${nav("a2")}</nav><button type="button" class="a2-theme" data-theme-toggle aria-label="Toggle light and dark theme">Light / dark</button></aside>
    <section class="a2-shell"><header class="a2-head"><span class="a2-pulse"></span><h1>Workflow control plane</h1><p>${html(c.notice)}</p></header><main class="a2-content">
      <section class="a2-view a2-v-workflows"><div class="a2-title"><div><p class="a2-kicker">Configured routes</p><h2>Workflows</h2></div><p>The topology is the roster: scan the line, then inspect its live overlay.</p></div>${routes}<section class="a2-overlay"><header><p class="a2-kicker">Selected run overlay</p><h3>${html(c.run.id)}</h3><p><strong>${html(c.run.state)}</strong> at ${html(c.run.step)} · ${html(c.run.elapsed)}</p><small>Cost ${html(c.run.cost)} · ${html(c.run.budget)}</small></header><div class="a2-evidence">${c.run.children.map(x => `<div><span>${html(x.state)}</span><b>${html(x.name)}</b><small>${html(x.result)}</small></div>`).join("")}</div></section></section>
      <section class="a2-view a2-v-agents"><div class="a2-title"><div><p class="a2-kicker">Roster supply</p><h2>Agents</h2></div><p>In use and available are assignment facts, not health states.</p></div><div class="a2-board"><div class="a2-row head"><div>Agent</div><div>Availability</div><div>Model</div><div>Authority ceiling</div><div>Workflow</div><div>Now</div></div>${c.agents.map(a => `<div class="a2-row"><div><strong>${html(a.name)}</strong><span>${html(a.harness)}</span></div><div class="a2-tag">${html(a.availability)}</div><div>${html(a.model)}</div><div>${html(a.ceiling)}</div><div>${html(a.workflows)}</div><div>${a.active ? `${a.active} live` : "Idle"}</div></div>`).join("")}</div></section>
      <section class="a2-view a2-v-runs"><div class="a2-title"><div><p class="a2-kicker">Run evidence</p><h2>Live / history</h2></div><p>Lifecycle, domain result, and verification stay independently legible.</p></div><div class="a2-livegrid"><section class="a2-panel"><p class="a2-kicker">Live now</p><h3>${html(c.run.id)}</h3>${[["Lifecycle",c.run.state],["Step",c.run.step],["Elapsed",c.run.elapsed],["Trigger",c.run.trigger],["Cost",c.run.cost]].map(x=>`<div class="a2-fact"><span>${html(x[0])}</span><b>${html(x[1])}</b></div>`).join("")}</section><section class="a2-panel"><p class="a2-kicker">History ledger</p><h3>Recent runs</h3>${c.recentRuns.map(r=>`<div class="a2-fact"><span><b>${html(r.workflow)}</b><br>${html(r.ref)}</span><b>${html(r.execution)} / ${html(r.domain)} / ${html(r.verification)} / ${html(r.cost)}</b></div>`).join("")}</section></div></section>
      <section class="a2-view a2-v-spend"><div class="a2-title"><div><p class="a2-kicker">Spend truth</p><h2>Controls / reporting</h2></div><p>Admission authority and after-the-fact cost are different systems.</p></div><div class="a2-livegrid"><section class="a2-panel"><p class="a2-kicker">Control hierarchy</p><h3>Scopes</h3>${c.spend.scopes.map((s,i)=>`<div class="a2-fact"><span>${html(s)}</span><b>${i===0?"Plane policy":i===2?"Configured":"Inherited"}</b></div>`).join("")}</section><section><div class="a2-coststates">${c.spend.truth.map(t=>`<div class="a2-cost"><strong>${html(t.label)}</strong><b>${html(t.value)}</b><span>${html(t.state)}</span></div>`).join("")}</div></section></div></section>
      <section class="a2-view a2-v-create"><div class="a2-title"><div><p class="a2-kicker">Goal first</p><h2>Create workflow</h2></div><p>Describe the outcome before choosing its machinery.</p></div>${createFlow(c,"a2")}</section>
    </main></section>
  </article>`;
}

function renderAnth3(c) {
  return `
  <article class="a3" data-view="workflows">
    <style>
      .a3{--sheet:#edf0f5;--cell:#f9f9fb;--ink:#211c35;--muted:#6e6a7c;--line:#bbb8c8;--violet:#503c82;--amber:#d58a21;--green:#2f765c;--red:#a14652;background:var(--sheet);color:var(--ink);font:12px/1.45 "SFMono-Regular","Roboto Mono",Consolas,monospace;height:100vh;min-height:640px;display:grid;grid-template-rows:auto auto minmax(0,1fr);overflow:hidden;color-scheme:light}
      @media(prefers-color-scheme:dark){.a3{--sheet:#191724;--cell:#22202f;--ink:#f0edf7;--muted:#aaa5b8;--line:#484359;--violet:#b6a3ef;--amber:#f0ae4c;--green:#70bd98;--red:#ee8992;color-scheme:dark}}
      html[data-theme="light"] .a3{--sheet:#edf0f5;--cell:#f9f9fb;--ink:#211c35;--muted:#6e6a7c;--line:#bbb8c8;--violet:#503c82;--amber:#d58a21;--green:#2f765c;--red:#a14652;color-scheme:light}html[data-theme="dark"] .a3{--sheet:#191724;--cell:#22202f;--ink:#f0edf7;--muted:#aaa5b8;--line:#484359;--violet:#b6a3ef;--amber:#f0ae4c;--green:#70bd98;--red:#ee8992;color-scheme:dark}
      .a3 *{box-sizing:border-box}.a3 button,.a3 textarea{font:inherit;color:inherit}.a3 button{cursor:pointer}.a3 button:focus-visible,.a3 textarea:focus-visible,.a3 summary:focus-visible{outline:3px solid var(--amber);outline-offset:-1px}.a3-mast{display:grid;grid-template-columns:250px 1fr auto;border-bottom:2px solid var(--ink);background:var(--cell);align-items:stretch}.a3-brand{font:800 24px/1 "Copperplate","Arial Narrow",sans-serif;letter-spacing:.08em;text-transform:uppercase;padding:18px 20px;border-right:1px solid var(--line)}.a3-brand span{color:var(--violet)}.a3-notice{align-self:center;padding:0 20px;color:var(--muted);font-size:10px;text-transform:uppercase;letter-spacing:.05em}.a3-theme{border:0;border-left:1px solid var(--line);background:transparent;padding:0 20px;font-weight:700}.a3-tabs{display:flex;background:var(--cell);border-bottom:1px solid var(--line)}.a3-tabs button{border:0;border-right:1px solid var(--line);background:transparent;padding:11px 18px;text-transform:uppercase;font-weight:800;font-size:10px;letter-spacing:.08em}.a3-tabs .a3-create{margin-left:auto;background:var(--violet);color:var(--cell)}.a3[data-view="workflows"] [data-nav="workflows"],.a3[data-view="agents"] [data-nav="agents"],.a3[data-view="runs"] [data-nav="runs"],.a3[data-view="spend"] [data-nav="spend"],.a3[data-view="create"] [data-nav="create"]{background:var(--ink);color:var(--cell)}
      .a3-main{min-height:0;overflow:auto}.a3-view{display:none;min-height:100%}.a3[data-view="workflows"] .a3-v-workflows,.a3[data-view="agents"] .a3-v-agents,.a3[data-view="runs"] .a3-v-runs,.a3[data-view="spend"] .a3-v-spend,.a3[data-view="create"] .a3-v-create{display:block}.a3-heading{display:flex;justify-content:space-between;align-items:end;padding:22px 20px 12px;border-bottom:1px solid var(--line)}.a3-heading h1{font:800 30px/.9 "Copperplate","Arial Narrow",sans-serif;text-transform:uppercase;letter-spacing:.03em;margin:0}.a3-heading p{margin:0;color:var(--muted)}.a3-label{font:800 9px/1 monospace;text-transform:uppercase;letter-spacing:.14em;color:var(--violet);margin:0 0 7px}
      .a3-ledger{min-width:980px}.a3-lrow{display:grid;grid-template-columns:220px 1.35fr .55fr .65fr .65fr .65fr .7fr;border-bottom:1px solid var(--line);background:var(--cell)}.a3-lrow>div{padding:12px 14px;border-right:1px solid var(--line);min-height:58px}.a3-lrow>div:last-child{border:0}.a3-lrow.head{background:var(--sheet);font-weight:800;font-size:9px;text-transform:uppercase;letter-spacing:.1em;color:var(--muted)}.a3-lrow.head>div{min-height:auto;padding-top:8px;padding-bottom:8px}.a3-lrow strong,.a3-lrow span{display:block}.a3-lrow span{color:var(--muted);font-size:10px;margin-top:4px}.a3-status{font-weight:800;text-transform:uppercase;color:var(--green)}.a3-status.draft{color:var(--muted)}.a3-status.blocked{color:var(--red)}.a3-status.executing{color:var(--amber)}
      .a3-expansion{display:grid;grid-template-columns:1.6fr .85fr;border-bottom:2px solid var(--ink);background:var(--sheet);min-width:980px}.a3-graphsheet{padding:20px;border-right:1px solid var(--line)}.a3-graphhead{display:flex;justify-content:space-between;align-items:start}.a3-graphhead h2{font:800 18px "Copperplate",sans-serif;text-transform:uppercase;margin:0}.a3-graphhead p{margin:3px 0;color:var(--muted)}.a3-select{border:1px solid var(--line);background:var(--cell);padding:8px 10px}.a3-topology{display:grid;grid-template-columns:repeat(7,auto);align-items:center;margin:26px 0 20px}.a3-topology b{border:1px solid var(--ink);background:var(--cell);padding:12px 10px;text-align:center;position:relative}.a3-topology b.current{border:3px double var(--violet);color:var(--violet)}.a3-topology b.current:after{content:"EXECUTING";position:absolute;top:-17px;left:-1px;font-size:8px;color:var(--amber)}.a3-topology i{font-style:normal;text-align:center;color:var(--violet);padding:0 8px}.a3-dimensions{display:grid;grid-template-columns:repeat(5,1fr);border:1px solid var(--line)}.a3-dimensions div{padding:9px;border-right:1px solid var(--line)}.a3-dimensions div:last-child{border:0}.a3-dimensions span{display:block;color:var(--muted);font-size:9px}.a3-dimensions b{display:block;margin-top:4px}.a3-overlay{padding:20px;background:var(--cell)}.a3-overlay h3{font:800 15px "Copperplate",sans-serif;text-transform:uppercase;margin:3px 0}.a3-overlay>p{color:var(--muted)}.a3-child{border-top:1px solid var(--line);padding:10px 0}.a3-child b,.a3-child span{display:block}.a3-child span{color:var(--muted);font-size:10px}
      .a3-gridtable{min-width:900px}.a3-grow{display:grid;border-bottom:1px solid var(--line);background:var(--cell)}.a3-agentrow{grid-template-columns:1fr .7fr 1fr .6fr 1.4fr 1.2fr}.a3-runrow{grid-template-columns:1.1fr .8fr .8fr .9fr .7fr}.a3-grow>div{padding:13px;border-right:1px solid var(--line)}.a3-grow.head{background:var(--sheet);font-size:9px;text-transform:uppercase;font-weight:800;color:var(--muted)}.a3-grow strong,.a3-grow span{display:block}.a3-grow span{color:var(--muted);font-size:10px}.a3-runhero{display:grid;grid-template-columns:1fr 2fr;border-bottom:2px solid var(--ink);background:var(--cell)}.a3-runhero>div{padding:20px;border-right:1px solid var(--line)}.a3-runhero h2{font:800 20px "Copperplate",sans-serif;text-transform:uppercase;margin:5px 0}.a3-evidencelist{display:grid;grid-template-columns:repeat(3,1fr)}.a3-evidencelist div{padding:20px;border-right:1px solid var(--line)}.a3-evidencelist span,.a3-evidencelist small{display:block;color:var(--muted)}
      .a3-spendmatrix{display:grid;grid-template-columns:260px 1fr;min-height:430px;background:var(--cell);border-bottom:2px solid var(--ink)}.a3-scopes{border-right:1px solid var(--line)}.a3-scopes h2,.a3-truths h2{font:800 18px "Copperplate",sans-serif;text-transform:uppercase;padding:18px;margin:0;border-bottom:1px solid var(--line)}.a3-scope{display:flex;justify-content:space-between;padding:14px 18px;border-bottom:1px solid var(--line)}.a3-scope b{color:var(--violet)}.a3-truths{min-width:0}.a3-truthrow{display:grid;grid-template-columns:140px 1fr 1fr;border-bottom:1px solid var(--line)}.a3-truthrow>*{padding:17px;border-right:1px solid var(--line)}.a3-truthrow strong{text-transform:uppercase;color:var(--violet)}
      .a3-v-create{padding:20px}.a3-createflow{display:grid;grid-template-columns:190px minmax(400px,1fr) 290px;background:var(--cell);border:1px solid var(--line);min-height:500px}.a3-steps{list-style:none;margin:0;padding:0;border-right:1px solid var(--line);counter-reset:step}.a3-steps li{padding:12px;border-bottom:1px solid var(--line);text-transform:uppercase;font-weight:800;font-size:10px}.a3-steps li span{color:var(--violet);margin-right:9px}.a3-steps li.current{background:var(--ink);color:var(--cell)}.a3-goal{padding:28px}.a3-goal h2{font:800 23px/1.1 "Copperplate",sans-serif;text-transform:uppercase}.a3-goal label{display:block;font-weight:800;text-transform:uppercase;font-size:10px;margin-top:22px}.a3-goal textarea{display:block;width:100%;margin-top:7px;padding:13px;border:1px solid var(--line);background:var(--sheet);resize:vertical}.a3-goal details{border:1px solid var(--line);margin-top:18px}.a3-goal summary{padding:12px;font-weight:800;text-transform:uppercase;cursor:pointer}.a3-goal summary span{float:right;color:var(--green)}.a3-goal details p{padding:0 13px;color:var(--muted)}.a3-goal details button,.a3-activation button{border:0;background:var(--violet);color:var(--cell);font-weight:800;text-transform:uppercase;padding:10px 13px;margin:0 13px 13px}.a3-activation{padding:28px;border-left:1px solid var(--line);background:var(--sheet)}.a3-activation h3{font:800 18px "Copperplate",sans-serif;text-transform:uppercase}.a3-check{display:block;border:1px solid var(--line);background:var(--cell);padding:12px;margin:24px 0 12px}.a3-activation button{margin:0;width:100%}.a3-activation button:disabled{opacity:.35}.a3-activation small{display:block;color:var(--muted);margin-top:12px}
      @media(max-width:850px){.a3{height:auto;min-height:100vh;overflow:visible}.a3-mast{grid-template-columns:1fr auto}.a3-notice{display:none}.a3-tabs{overflow:auto;position:sticky;top:0;z-index:5}.a3-tabs button{white-space:nowrap}.a3-tabs .a3-create{margin-left:0}.a3-expansion,.a3-runhero,.a3-spendmatrix,.a3-createflow{grid-template-columns:1fr}.a3-graphsheet,.a3-scopes,.a3-activation{border-right:0;border-bottom:1px solid var(--line)}.a3-createflow{min-height:0}.a3-steps{display:flex;overflow:auto}.a3-steps li{white-space:nowrap}.a3-heading{align-items:start;gap:10px}.a3-heading p{max-width:45%}}
      @media(prefers-reduced-motion:reduce){.a3 *{transition:none!important}}
    </style>
    <header class="a3-mast"><div class="a3-brand">Bitter<span>blossom</span></div><p class="a3-notice">${html(c.notice)}</p><button type="button" class="a3-theme" data-theme-toggle aria-label="Toggle light and dark theme">Theme ◐</button></header>
    <nav class="a3-tabs" aria-label="Primary">${nav("a3")}</nav>
    <main class="a3-main">
      <section class="a3-view a3-v-workflows"><header class="a3-heading"><div><p class="a3-label">Configuration ledger / 02 definitions</p><h1>Workflows</h1></div><p>One row per durable workflow. Expand a row to inspect its stable graph and run overlay.</p></header><div class="a3-ledger"><div class="a3-lrow head"><div>Workflow</div><div>Trigger</div><div>State</div><div>Now</div><div>Latest execution</div><div>Domain / proof</div><div>Spend</div></div>${c.workflows.map((w,i)=>`<div class="a3-lrow"><div><strong>${html(w.name)}</strong><span>${html(w.budget)}</span></div><div><strong>${html(w.trigger)}</strong><span>${i===0?"Trigger listening":"Trigger inactive"}</span></div><div class="a3-status ${i?"draft":""}">${html(w.lifecycle)}</div><div>${w.active?`<strong class="a3-status executing">${w.active} executing</strong><span>${html(c.run.step)}</span>`:'<strong>No active run</strong><span>Configured only</span>'}</div><div><strong>${html(w.latestExecution)}</strong></div><div><strong class="${w.latestDomain==="Blocked"?"a3-status blocked":""}">${html(w.latestDomain)}</strong><span>${html(w.verification)}</span></div><div><strong>${html(w.cost)}</strong></div></div>`).join("")}</div><section class="a3-expansion"><div class="a3-graphsheet"><div class="a3-graphhead"><div><p class="a3-label">Expanded definition</p><h2>PR Review · stable topology</h2><p>${html(c.workflows[0].trigger)}</p></div><button type="button" class="a3-select">Overlay: ${html(c.run.id)} ▾</button></div><div class="a3-topology">${c.workflows[0].topology.map((n,i)=>`${i?'<i>──→</i>':''}<b class="${i===2?'current':''}">${html(n)}</b>`).join("")}</div><div class="a3-dimensions"><div><span>Workflow</span><b>Active</b></div><div><span>Trigger</span><b>Listening</b></div><div><span>Run</span><b>Executing</b></div><div><span>Domain</span><b>Pending</b></div><div><span>Verification</span><b>In progress</b></div></div></div><aside class="a3-overlay"><p class="a3-label">Run overlay</p><h3>${html(c.run.id)}</h3><p>${html(c.run.elapsed)} · ${html(c.run.budget)} · cost ${html(c.run.cost)}</p>${c.run.children.map(x=>`<div class="a3-child"><b>${html(x.name)} · ${html(x.state)}</b><span>${html(x.result)}</span></div>`).join("")}</aside></section></section>
      <section class="a3-view a3-v-agents"><header class="a3-heading"><div><p class="a3-label">Roster ledger</p><h1>Agents</h1></div><p>Availability and assignment are explicit columns.</p></header><div class="a3-gridtable"><div class="a3-grow a3-agentrow head"><div>Agent</div><div>Availability</div><div>Model</div><div>Harness</div><div>Authority ceiling</div><div>Workflow / now</div></div>${c.agents.map(a=>`<div class="a3-grow a3-agentrow"><div><strong>${html(a.name)}</strong></div><div class="a3-status">${html(a.availability)}</div><div>${html(a.model)}</div><div>${html(a.harness)}</div><div>${html(a.ceiling)}</div><div><strong>${html(a.workflows)}</strong><span>${a.active?`${a.active} active run`:"No active run"}</span></div></div>`).join("")}</div></section>
      <section class="a3-view a3-v-runs"><header class="a3-heading"><div><p class="a3-label">Evidence ledger</p><h1>Runs</h1></div><p>Live execution above; immutable history below.</p></header><div class="a3-runhero"><div><p class="a3-label">Live / executing</p><h2>${html(c.run.id)}</h2><p>${html(c.run.trigger)} · ${html(c.run.elapsed)}</p><strong>${html(c.run.step)} · cost ${html(c.run.cost)}</strong></div><div class="a3-evidencelist">${c.run.children.map(x=>`<div><span>${html(x.state)}</span><b>${html(x.name)}</b><small>${html(x.result)}</small></div>`).join("")}</div></div><div class="a3-gridtable"><div class="a3-grow a3-runrow head"><div>Workflow / ref</div><div>Execution lifecycle</div><div>Domain result</div><div>Verification</div><div>Cost</div></div>${c.recentRuns.map(r=>`<div class="a3-grow a3-runrow"><div><strong>${html(r.workflow)}</strong><span>${html(r.ref)}</span></div><div>${html(r.execution)}</div><div class="${r.domain==='Blocked'?'a3-status blocked':''}">${html(r.domain)}</div><div>${html(r.verification)}</div><div>${html(r.cost)}</div></div>`).join("")}</div></section>
      <section class="a3-view a3-v-spend"><header class="a3-heading"><div><p class="a3-label">Policy / accounting</p><h1>Spend</h1></div><p>Unknown cost remains unknown; no substitution with zero.</p></header><section class="a3-spendmatrix"><div class="a3-scopes"><h2>Control scopes</h2>${c.spend.scopes.map((s,i)=>`<div class="a3-scope"><span>${html(s)}</span><b>${i===2?'SET':'POLICY'}</b></div>`).join("")}</div><div class="a3-truths"><h2>Reporting truth table</h2>${c.spend.truth.map(t=>`<div class="a3-truthrow"><strong>${html(t.label)}</strong><span>${html(t.value)}</span><span>${html(t.state)}</span></div>`).join("")}<div class="a3-truthrow"><strong>Current run</strong><span>${html(c.run.cost)}</span><span>Coverage gap · never treated as $0</span></div></div></section></section>
      <section class="a3-view a3-v-create"><header class="a3-heading"><div><p class="a3-label">New definition</p><h1>Create workflow</h1></div><p>The goal is reviewed before the configuration sequence proceeds.</p></header>${createFlow(c,"a3")}</section>
    </main>
  </article>`;
}

export const SPECS = {
  "ANTH-1": {
    label: "Pinned run inspector",
    move: "A dense workflow scan-table stays beside one stable topology while the selected run occupies a persistent evidence inspector.",
    philosophy: "Typography-led operational clarity with one signature split-pane instrument and restrained state color.",
    render: renderAnth1
  },
  "ANTH-2": {
    label: "Topology route map",
    move: "Inverts the roster-table assumption: each configured workflow is a navigable route whose stops are its agents and outcomes.",
    philosophy: "The fleet borrows the legible grammar of a transit control room without decorative simulation or fake telemetry.",
    render: renderAnth2
  },
  "ANTH-3": {
    label: "Expandable control ledger",
    move: "A full-width configuration ledger expands the chosen workflow in place, keeping lifecycle, domain result, proof, and cost as independent columns.",
    philosophy: "A typographic operator register uses structural rules as data relationships and reserves expressive type for hierarchy.",
    render: renderAnth3
  }
};
