const esc = (value) => String(value ?? "").replace(/[&<>"']/g, character => ({
  "&": "&amp;",
  "<": "&lt;",
  ">": "&gt;",
  '"': "&quot;",
  "'": "&#39;"
}[character]));

const steps = (items, className = "") => items.map((item, index) => `
  <li class="${className}">
    <span class="step-no">${String(index + 1).padStart(2, "0")}</span>
    <strong>${esc(item)}</strong>
  </li>`).join("");

const workflowRows = (corpus, className = "") => corpus.workflows.map((workflow, index) => `
  <article class="${className}" aria-label="${esc(workflow.name)} workflow">
    <span class="serial">WF-${String(index + 1).padStart(2, "0")}</span>
    <h3>${esc(workflow.name)}</h3>
    <dl>
      <div><dt>Lifecycle</dt><dd>${esc(workflow.lifecycle)}</dd></div>
      <div><dt>Trigger</dt><dd>${esc(workflow.trigger)}</dd></div>
      <div><dt>Active runs</dt><dd>${esc(workflow.active)}</dd></div>
      <div><dt>Instance state</dt><dd>${workflow.active === 0 ? "No active run" : `${esc(workflow.active)} active`}</dd></div>
      <div><dt>Execution</dt><dd>${esc(workflow.latestExecution)}</dd></div>
      <div><dt>Domain result</dt><dd>${esc(workflow.latestDomain)}</dd></div>
      <div><dt>Verification</dt><dd>${esc(workflow.verification)}</dd></div>
      <div><dt>Cost</dt><dd>${esc(workflow.cost)}</dd></div>
    </dl>
  </article>`).join("");

const topology = (workflow, run, className = "") => workflow.topology.map((node, index) => {
  const state = node === run.step ? "executing" : index < workflow.topology.indexOf(run.step) ? "complete" : "pending";
  return `
    <li class="${className}" data-state="${state}">
      <span class="node-index">${String(index + 1).padStart(2, "0")}</span>
      <strong>${esc(node)}</strong>
      <small>${state === "executing" ? esc(run.state) : state === "complete" ? "Step complete" : "Awaiting input"}</small>
    </li>`;
}).join("");

const agentRows = (corpus, className = "") => corpus.agents.map((agent, index) => `
  <article class="${className}">
    <header><span>AG-${String(index + 1).padStart(2, "0")}</span><strong>${esc(agent.availability)}</strong></header>
    <h3>${esc(agent.name)}</h3>
    <dl>
      <div><dt>Model</dt><dd>${esc(agent.model)}</dd></div>
      <div><dt>Harness</dt><dd>${esc(agent.harness)}</dd></div>
      <div><dt>Authority ceiling</dt><dd>${esc(agent.ceiling)}</dd></div>
      <div><dt>Workflow use</dt><dd>${esc(agent.workflows)}</dd></div>
      <div><dt>Active runs</dt><dd>${esc(agent.active)}</dd></div>
    </dl>
  </article>`).join("");

const runRows = (corpus) => corpus.recentRuns.map((run, index) => `
  <tr>
    <td>${String(index + 1).padStart(2, "0")}</td>
    <th scope="row">${esc(run.workflow)}<small>${esc(run.ref)}</small></th>
    <td>${esc(run.execution)}</td>
    <td>${esc(run.domain)}</td>
    <td>${esc(run.verification)}</td>
    <td>${esc(run.cost)}</td>
  </tr>`).join("");

const spendTruth = (corpus, className = "") => corpus.spend.truth.map((item, index) => `
  <article class="${className}">
    <span>${String(index + 1).padStart(2, "0")}</span>
    <h3>${esc(item.label)}</h3>
    <strong>${esc(item.value)}</strong>
    <p>${esc(item.state)}</p>
  </article>`).join("");

const viewButtons = (prefix) => [
  ["workflows", "Workflows"],
  ["agents", "Agents"],
  ["runs", "Runs"],
  ["spend", "Spend"],
  ["create", "Create workflow"]
].map(([view, label], index) => `<button type="button" data-view="${view}" ${index === 0 ? "aria-current=\"true\"" : ""}><span>${prefix}${String(index + 1).padStart(2, "0")}</span>${label}</button>`).join("");

function renderLedger(corpus) {
  const selected = corpus.workflows[0];
  return `
<div class="brut brut-ledger">
  <style>
    .brut-ledger{--paper:#e9e7df;--ink:#0b0b0a;--muted:#5e5d57;--line:#0b0b0a;--accent:#d71919;--wash:#d8d5ca;min-height:100vh;background:var(--paper);color:var(--ink);font-family:Arial,Helvetica,sans-serif;display:grid;grid-template-columns:12.5rem minmax(0,1fr);grid-template-rows:auto 1fr;letter-spacing:-.01em}
    :root[data-theme="dark"] .brut-ledger{--paper:#11110f;--ink:#eeeae0;--muted:#aaa69d;--line:#eeeae0;--accent:#ff3434;--wash:#292824}
    .brut-ledger *{box-sizing:border-box}.brut-ledger button{font:inherit;color:inherit}.brut-ledger button:focus-visible{outline:4px solid var(--accent);outline-offset:-4px}.brut-ledger [hidden]{display:none!important}
    .brut-ledger .mast{grid-column:1/-1;display:grid;grid-template-columns:12.5rem minmax(0,1fr) auto;border-bottom:3px solid var(--line);min-height:5.5rem}
    .brut-ledger .mark{display:grid;place-items:center;background:var(--ink);color:var(--paper);font:bold 2rem/1 monospace;border-right:1px solid var(--line)}
    .brut-ledger .title{padding:.7rem 1rem;display:flex;align-items:end;gap:1rem}.brut-ledger .title strong{font-size:clamp(2.2rem,5.5vw,5rem);line-height:.78;letter-spacing:-.07em;text-transform:uppercase}.brut-ledger .title small{max-width:24ch;font:600 .64rem/1.25 monospace;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}
    .brut-ledger .theme{border:0;border-left:1px solid var(--line);background:var(--accent);color:#fff;padding:0 1.25rem;font:700 .68rem/1 monospace;text-transform:uppercase;letter-spacing:.08em;cursor:pointer}
    .brut-ledger .rail{border-right:1px solid var(--line);display:flex;flex-direction:column;min-height:calc(100vh - 5.5rem)}
    .brut-ledger .notice{padding:.75rem;border-bottom:1px solid var(--line);font:700 .61rem/1.35 monospace;text-transform:uppercase;letter-spacing:.07em;color:var(--muted)}
    .brut-ledger nav{display:grid}.brut-ledger nav button{border:0;border-bottom:1px solid var(--line);background:transparent;display:grid;grid-template-columns:2.6rem 1fr;text-align:left;padding:0;min-height:3.35rem;align-items:stretch;text-transform:uppercase;font:bold .72rem/1 monospace;cursor:pointer}
    .brut-ledger nav button span{display:grid;place-items:center;border-right:1px solid var(--line);font:400 .62rem monospace;color:var(--muted)}.brut-ledger nav button[aria-current]{background:var(--ink);color:var(--paper)}.brut-ledger nav button[aria-current] span{color:var(--paper);border-color:var(--paper)}
    .brut-ledger .rail-foot{margin-top:auto;padding:.75rem;font:600 .6rem/1.5 monospace;text-transform:uppercase;letter-spacing:.07em;border-top:1px solid var(--line)}
    .brut-ledger main{min-width:0}.brut-ledger [data-panel]{min-height:calc(100vh - 5.5rem)}
    .brut-ledger .workflow-panel{display:grid;grid-template-columns:minmax(18rem,.8fr) minmax(24rem,1.35fr) minmax(16rem,.75fr)}
    .brut-ledger .zone{min-width:0;border-right:1px solid var(--line)}.brut-ledger .zone:last-child{border-right:0}.brut-ledger .zone-title{padding:.55rem .75rem;border-bottom:1px solid var(--line);font:700 .63rem/1 monospace;text-transform:uppercase;letter-spacing:.1em;background:var(--wash);display:flex;justify-content:space-between}
    .brut-ledger .wf-card{padding:1rem;border-bottom:1px solid var(--line);position:relative}.brut-ledger .wf-card:first-of-type{border-left:.5rem solid var(--accent)}.brut-ledger .serial{font:.62rem monospace;color:var(--muted)}.brut-ledger .wf-card h3{margin:.65rem 0 1rem;font-size:clamp(1.8rem,3.2vw,3.8rem);line-height:.88;letter-spacing:-.055em;text-transform:uppercase}.brut-ledger dl{margin:0}.brut-ledger dl>div{display:grid;grid-template-columns:7rem 1fr;border-top:1px solid var(--line);padding:.42rem 0;gap:.6rem}.brut-ledger dt{font:600 .58rem/1.25 monospace;text-transform:uppercase;letter-spacing:.06em;color:var(--muted)}.brut-ledger dd{margin:0;font:700 .68rem/1.25 monospace;text-transform:uppercase}
    .brut-ledger .graph-head{padding:1rem;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:1rem}.brut-ledger .graph-head h2{font-size:clamp(2.5rem,5vw,6.5rem);line-height:.8;letter-spacing:-.07em;text-transform:uppercase;margin:.4rem 0}.brut-ledger .graph-head output{font:700 .72rem monospace;text-transform:uppercase;color:var(--accent)}
    .brut-ledger .topology{list-style:none;padding:1rem;margin:0;display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:0}.brut-ledger .topology li{border:1px solid var(--line);border-right:0;min-height:9.5rem;padding:.65rem;display:grid;grid-template-rows:auto 1fr auto}.brut-ledger .topology li:last-child{border-right:1px solid var(--line)}.brut-ledger .topology [data-state="executing"]{background:var(--accent);color:#fff}.brut-ledger .topology [data-state="complete"] strong{text-decoration:line-through;text-decoration-thickness:.18rem}.brut-ledger .topology strong{align-self:center;font-size:clamp(.8rem,1.4vw,1.35rem);text-transform:uppercase}.brut-ledger .topology small,.brut-ledger .node-index{font:.58rem/1.2 monospace;text-transform:uppercase;letter-spacing:.05em}
    .brut-ledger .overlay{margin:0 1rem 1rem;border:1px solid var(--line)}.brut-ledger .overlay header{display:flex;justify-content:space-between;padding:.5rem;background:var(--ink);color:var(--paper);font:.62rem monospace;text-transform:uppercase}.brut-ledger .overlay-item{display:grid;grid-template-columns:1fr auto;padding:.55rem;border-top:1px solid var(--line);gap:.5rem;font:600 .64rem/1.3 monospace;text-transform:uppercase}.brut-ledger .overlay-item:first-of-type{border-top:0}.brut-ledger .overlay-item small{grid-column:1/-1;color:var(--muted)}
    .brut-ledger .evidence{padding:.75rem}.brut-ledger .evidence h3{font-size:1.6rem;text-transform:uppercase;margin:.25rem 0 1rem}.brut-ledger .readout{border-top:6px solid var(--accent);padding:.75rem 0}.brut-ledger .readout output{font:bold 1.1rem monospace;text-transform:uppercase}.brut-ledger .readout p{font:.64rem/1.4 monospace;text-transform:uppercase;color:var(--muted)}
    .brut-ledger .full-panel{padding:1rem}.brut-ledger .panel-head{display:grid;grid-template-columns:1fr auto;align-items:end;border-bottom:6px solid var(--line);padding-bottom:.8rem}.brut-ledger .panel-head h2{margin:0;font-size:clamp(3rem,8vw,8rem);line-height:.72;text-transform:uppercase;letter-spacing:-.07em}.brut-ledger .panel-head p{max-width:32ch;font:600 .68rem/1.35 monospace;text-transform:uppercase}
    .brut-ledger .agent-grid,.brut-ledger .truth-grid{display:grid;grid-template-columns:repeat(3,1fr);border-left:1px solid var(--line);margin-top:1rem}.brut-ledger .agent-card,.brut-ledger .truth-card{border:1px solid var(--line);border-left:0;padding:.75rem}.brut-ledger .agent-card header{display:flex;justify-content:space-between;font:.6rem monospace;text-transform:uppercase}.brut-ledger .agent-card header strong{color:var(--accent)}.brut-ledger .agent-card h3{font-size:clamp(1.6rem,3.2vw,3.5rem);text-transform:uppercase;line-height:.9;margin:2.5rem 0 1rem}.brut-ledger table{border-collapse:collapse;width:100%;margin-top:1rem;font:.68rem/1.25 monospace;text-transform:uppercase}.brut-ledger th,.brut-ledger td{border:1px solid var(--line);padding:.7rem;text-align:left}.brut-ledger th{font-size:.78rem}.brut-ledger th small{display:block;color:var(--muted);margin-top:.3rem}.brut-ledger thead{background:var(--ink);color:var(--paper)}
    .brut-ledger .spend-scope{display:flex;flex-wrap:wrap;border:1px solid var(--line);margin-top:1rem}.brut-ledger .spend-scope span{padding:.75rem;flex:1;border-right:1px solid var(--line);font:.65rem monospace;text-transform:uppercase}.brut-ledger .spend-scope span:last-child{border:0}.brut-ledger .truth-card h3{font-size:2rem;text-transform:uppercase;margin:3rem 0 .5rem}.brut-ledger .truth-card strong,.brut-ledger .truth-card p{font:.65rem/1.4 monospace;text-transform:uppercase}.brut-ledger .create-grid{display:grid;grid-template-columns:14rem 1fr;margin-top:1rem;border:1px solid var(--line)}.brut-ledger .create-steps{list-style:none;margin:0;padding:0;border-right:1px solid var(--line)}.brut-ledger .create-steps li{display:grid;grid-template-columns:3rem 1fr;border-bottom:1px solid var(--line);min-height:3rem;align-items:center;font:.65rem monospace;text-transform:uppercase}.brut-ledger .create-steps li:first-child{background:var(--accent);color:#fff}.brut-ledger .step-no{display:grid;place-items:center;height:100%;border-right:1px solid currentColor}.brut-ledger .create-steps strong{padding:.5rem}.brut-ledger .goal-review{padding:1rem}.brut-ledger .goal-review h3{font-size:2rem;text-transform:uppercase;margin:0 0 1rem}.brut-ledger .goal-block{display:grid;grid-template-columns:8rem 1fr;border-top:1px solid var(--line);padding:.75rem 0}.brut-ledger .goal-block span{font:.58rem monospace;text-transform:uppercase;color:var(--muted)}.brut-ledger .goal-block p{margin:0;font:700 .76rem/1.55 monospace}.brut-ledger .test-block{border:3px solid var(--accent);padding:.8rem;margin-top:1rem;font:.7rem/1.4 monospace;text-transform:uppercase}
    @media(max-width:980px){.brut-ledger{grid-template-columns:9rem 1fr}.brut-ledger .mast{grid-template-columns:9rem 1fr auto}.brut-ledger .workflow-panel{grid-template-columns:1fr}.brut-ledger .zone{border-right:0;border-bottom:1px solid var(--line)}.brut-ledger .agent-grid,.brut-ledger .truth-grid{grid-template-columns:1fr}.brut-ledger .topology{grid-template-columns:1fr 1fr}.brut-ledger .topology li:nth-child(2){border-right:1px solid var(--line)}}
    @media(max-width:620px){.brut-ledger{display:block}.brut-ledger .mast{display:grid;grid-template-columns:4rem 1fr}.brut-ledger .mark{grid-row:1/3}.brut-ledger .title{min-width:0}.brut-ledger .title strong{font-size:2rem}.brut-ledger .title small{display:none}.brut-ledger .theme{grid-column:2;border-left:0;border-top:1px solid var(--line);padding:.65rem}.brut-ledger .rail{min-height:0;border-right:0}.brut-ledger nav{grid-template-columns:repeat(5,1fr)}.brut-ledger nav button{grid-template-columns:1fr;text-align:center;padding:.55rem .2rem;font-size:.55rem}.brut-ledger nav button span{border:0;margin-bottom:.3rem}.brut-ledger .notice,.brut-ledger .rail-foot{display:none}.brut-ledger [data-panel]{min-height:0}.brut-ledger .topology{grid-template-columns:1fr}.brut-ledger .topology li{border-right:1px solid var(--line);min-height:6rem}.brut-ledger .create-grid{grid-template-columns:1fr}.brut-ledger .create-steps{border-right:0}.brut-ledger .panel-head{display:block}.brut-ledger .panel-head p{margin-top:1rem}.brut-ledger table{display:block;overflow:auto}}
    @media(prefers-reduced-motion:reduce){.brut-ledger *{scroll-behavior:auto!important}}
  </style>
  <header class="mast">
    <div class="mark" aria-hidden="true">BB®</div>
    <div class="title"><strong>Control<br>Ledger</strong><small>Unattended workflow plane / operator surface / revision 03</small></div>
    <button class="theme" type="button" data-theme-toggle>Invert substrate</button>
  </header>
  <aside class="rail">
    <p class="notice">${esc(corpus.notice)}</p>
    <nav aria-label="Primary">${viewButtons("L/")}</nav>
    <p class="rail-foot">System state is plural.<br>Lifecycle ≠ execution ≠ result ≠ verification.<br><br>BB / REV 03</p>
  </aside>
  <main>
    <section class="workflow-panel" data-panel="workflows">
      <div class="zone"><div class="zone-title"><span>Configured roster</span><span>${corpus.workflows.length} records</span></div>${workflowRows(corpus,"wf-card")}</div>
      <div class="zone">
        <div class="zone-title"><span>Stable topology</span><span>Selected / ${esc(selected.name)}</span></div>
        <div class="graph-head"><div><span class="serial">WORKFLOW / ACTIVE</span><h2>${esc(selected.name)}</h2></div><output>${esc(corpus.run.state)} · ${esc(corpus.run.elapsed)}</output></div>
        <ol class="topology">${topology(selected,corpus.run)}</ol>
        <div class="overlay"><header><span>Run overlay / ${esc(corpus.run.id)}</span><span>Trigger / ${esc(corpus.run.trigger)}</span></header>${corpus.run.children.map(child=>`<div class="overlay-item"><strong>${esc(child.name)}</strong><span>${esc(child.state)}</span><small>${esc(child.result)}</small></div>`).join("")}</div>
      </div>
      <aside class="zone"><div class="zone-title"><span>Evidence register</span><span>Live overlay</span></div><div class="evidence"><h3>Separate truth channels</h3><div class="readout"><dt>Execution</dt><output>${esc(corpus.run.state)}</output><p>Current run lifecycle; not the domain result.</p></div><div class="readout"><dt>Latest domain result</dt><output>${esc(selected.latestDomain)}</output><p>The prior execution succeeded while findings blocked the reviewed change.</p></div><div class="readout"><dt>Verification</dt><output>${esc(selected.verification)}</output><p>Evidence was achieved for the latest completed run.</p></div><div class="readout"><dt>Cost</dt><output>${esc(corpus.run.cost)}</output><p>Unknown cost remains unknown; it is never rendered as zero.</p></div></div></aside>
    </section>
    <section class="full-panel" data-panel="agents" hidden><header class="panel-head"><h2>Agents</h2><p>Roster definitions separated by whether a configured workflow currently commissions them.</p></header><div class="agent-grid">${agentRows(corpus,"agent-card")}</div></section>
    <section class="full-panel" data-panel="runs" hidden><header class="panel-head"><h2>Run evidence</h2><p>Execution state, domain outcome, verification state, and cost truth remain independent columns.</p></header><table><thead><tr><th>#</th><th>Workflow / reference</th><th>Execution</th><th>Domain</th><th>Verification</th><th>Cost</th></tr></thead><tbody>${runRows(corpus)}</tbody></table></section>
    <section class="full-panel" data-panel="spend" hidden><header class="panel-head"><h2>Spend</h2><p>Admission controls define ceilings. Receipts and estimates report actual use with explicit provenance.</p></header><div class="spend-scope">${corpus.spend.scopes.map(scope=>`<span>${esc(scope)}</span>`).join("")}</div><div class="truth-grid">${spendTruth(corpus,"truth-card")}</div></section>
    <section class="full-panel" data-panel="create" hidden><header class="panel-head"><h2>Create</h2><p>Workflow-first. State the outcome before selecting triggers, agents, authority, or limits.</p></header><div class="create-grid"><ol class="create-steps">${steps(corpus.creation.steps)}</ol><div class="goal-review"><h3>01 / Goal review</h3><div class="goal-block"><span>Operator goal</span><p>${esc(corpus.creation.rawGoal)}</p></div><div class="goal-block"><span>Enhanced goal</span><p>${esc(corpus.creation.enhancedGoal)}</p></div><div class="test-block"><strong>Activation interlock</strong><br>${esc(corpus.creation.test)}<br><br>Draft until the test produces inspectable evidence.</div></div></div></section>
  </main>
</div>`;
}

function renderFoldout(corpus) {
  const selected = corpus.workflows[0];
  return `
<div class="brut brut-foldout">
  <style>
    .brut-foldout{--paper:#f1efe7;--ink:#10100f;--muted:#66635b;--line:#10100f;--accent:#df1f1f;--panel:#ddd9cd;min-height:100vh;background:var(--paper);color:var(--ink);font-family:Arial,Helvetica,sans-serif;padding:.65rem}
    :root[data-theme="dark"] .brut-foldout{--paper:#121210;--ink:#f0ede4;--muted:#aaa69d;--line:#f0ede4;--accent:#ff3838;--panel:#292824}
    .brut-foldout *{box-sizing:border-box}.brut-foldout button{font:inherit;color:inherit}.brut-foldout button:focus-visible{outline:4px solid var(--accent);outline-offset:2px}.brut-foldout [hidden]{display:none!important}
    .brut-foldout .sheet{min-height:calc(100vh - 1.3rem);border:2px solid var(--line);display:grid;grid-template-rows:auto auto 1fr}
    .brut-foldout .folio{display:grid;grid-template-columns:1fr auto;border-bottom:2px solid var(--line);min-height:8rem}.brut-foldout .folio-title{padding:.7rem;display:flex;align-items:flex-end;justify-content:space-between;gap:2rem;overflow:hidden}.brut-foldout .folio-title h1{margin:0;font-size:clamp(4rem,10vw,11rem);line-height:.65;letter-spacing:-.085em;text-transform:uppercase}.brut-foldout .folio-title p{font:700 .62rem/1.35 monospace;text-transform:uppercase;letter-spacing:.08em;max-width:34ch;margin:0}.brut-foldout .theme{border:0;border-left:2px solid var(--line);background:transparent;min-width:9rem;padding:.8rem;font:bold .62rem/1.3 monospace;text-transform:uppercase;letter-spacing:.08em;cursor:pointer}.brut-foldout .theme:before{content:"◐";display:block;font-size:2rem;margin-bottom:.5rem;color:var(--accent)}
    .brut-foldout .tabs{display:grid;grid-template-columns:repeat(5,1fr);border-bottom:2px solid var(--line)}.brut-foldout .tabs button{background:transparent;border:0;border-right:1px solid var(--line);padding:.7rem;text-align:left;text-transform:uppercase;font:bold .67rem/1.2 monospace;cursor:pointer;display:flex;justify-content:space-between;gap:.5rem}.brut-foldout .tabs button:last-child{border-right:0}.brut-foldout .tabs button span{color:var(--muted)}.brut-foldout .tabs button[aria-current]{background:var(--accent);color:#fff}.brut-foldout .tabs button[aria-current] span{color:#fff}
    .brut-foldout .notice{margin:0;padding:.45rem .7rem;border-bottom:1px solid var(--line);font:600 .58rem/1.3 monospace;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}
    .brut-foldout .roster-strip{display:grid;grid-template-columns:repeat(2,1fr);border-bottom:2px solid var(--line)}.brut-foldout .roster-card{display:grid;grid-template-columns:4.6rem 1fr 12rem;min-height:12rem;border-right:1px solid var(--line)}.brut-foldout .roster-card:last-child{border-right:0}.brut-foldout .roster-card .serial{padding:.65rem;border-right:1px solid var(--line);writing-mode:vertical-rl;font:.62rem monospace;text-transform:uppercase}.brut-foldout .roster-card h3{font-size:clamp(2rem,4vw,4.5rem);line-height:.82;letter-spacing:-.06em;text-transform:uppercase;margin:.75rem}.brut-foldout .roster-card dl{margin:0;border-left:1px solid var(--line);font:.58rem/1.2 monospace;text-transform:uppercase}.brut-foldout .roster-card dl>div{padding:.4rem;border-bottom:1px solid var(--line)}.brut-foldout .roster-card dt{color:var(--muted);margin-bottom:.15rem}.brut-foldout .roster-card dd{margin:0;font-weight:700}.brut-foldout .roster-card:first-child{box-shadow:inset 0 .55rem var(--accent)}
    .brut-foldout .fold{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(17rem,.5fr);min-height:28rem}.brut-foldout .diagram{border-right:2px solid var(--line);padding:.75rem;position:relative}.brut-foldout .section-label{display:flex;justify-content:space-between;font:700 .6rem/1 monospace;text-transform:uppercase;letter-spacing:.08em}.brut-foldout .diagram h2{font-size:clamp(3.5rem,8vw,9rem);line-height:.72;letter-spacing:-.075em;text-transform:uppercase;margin:2.5rem 0 1.5rem;max-width:7ch}.brut-foldout .topology{list-style:none;margin:0;padding:0;display:grid;grid-template-columns:repeat(4,1fr);align-items:stretch}.brut-foldout .topology li{min-height:8rem;border:2px solid var(--line);border-right:0;padding:.5rem;display:grid;grid-template-rows:auto 1fr auto}.brut-foldout .topology li:last-child{border-right:2px solid var(--line)}.brut-foldout .topology [data-state="executing"]{background:var(--accent);color:#fff}.brut-foldout .topology strong{align-self:center;text-transform:uppercase;font-size:clamp(.75rem,1.6vw,1.25rem)}.brut-foldout .topology small,.brut-foldout .node-index{font:.55rem/1.2 monospace;text-transform:uppercase}.brut-foldout .overlay-line{display:grid;grid-template-columns:repeat(4,1fr);margin-top:.7rem;border:1px solid var(--line);font:.58rem/1.3 monospace;text-transform:uppercase}.brut-foldout .overlay-line span{padding:.55rem;border-right:1px solid var(--line)}.brut-foldout .overlay-line span:last-child{border:0}.brut-foldout .telemetry{display:grid;grid-template-rows:auto 1fr}.brut-foldout .telemetry header{background:var(--ink);color:var(--paper);padding:.7rem;font:700 .62rem monospace;text-transform:uppercase;display:flex;justify-content:space-between}.brut-foldout .telemetry-grid{display:grid;grid-template-columns:1fr 1fr}.brut-foldout .readout{padding:.7rem;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.brut-foldout .readout:nth-child(even){border-right:0}.brut-foldout .readout dt{font:.57rem monospace;text-transform:uppercase;color:var(--muted)}.brut-foldout .readout dd{margin:1.2rem 0 0;font:bold 1rem/1.1 monospace;text-transform:uppercase}.brut-foldout .readout p{font:.56rem/1.35 monospace;text-transform:uppercase;color:var(--muted)}
    .brut-foldout .panel{padding:.75rem}.brut-foldout .panel-title{display:grid;grid-template-columns:auto 1fr;align-items:end;border-bottom:7px solid var(--line);padding-bottom:.75rem;gap:1rem}.brut-foldout .panel-title span{font:4rem/.75 monospace;color:var(--accent)}.brut-foldout .panel-title h2{font-size:clamp(3rem,8vw,9rem);line-height:.7;text-transform:uppercase;letter-spacing:-.08em;margin:0}.brut-foldout .panel-intro{font:600 .68rem/1.4 monospace;text-transform:uppercase;max-width:70ch;margin:1rem 0 2rem}
    .brut-foldout .agent-grid{display:grid;grid-template-columns:repeat(3,1fr);border:2px solid var(--line)}.brut-foldout .agent-card{padding:.7rem;border-right:1px solid var(--line)}.brut-foldout .agent-card:last-child{border:0}.brut-foldout .agent-card header{display:flex;justify-content:space-between;font:.58rem monospace;text-transform:uppercase}.brut-foldout .agent-card header strong{color:var(--accent)}.brut-foldout .agent-card h3{font-size:clamp(2rem,4vw,5rem);line-height:.82;text-transform:uppercase;letter-spacing:-.06em;margin:4rem 0 1rem}.brut-foldout .agent-card dl>div{border-top:1px solid var(--line);padding:.5rem 0}.brut-foldout .agent-card dt{font:.56rem monospace;text-transform:uppercase;color:var(--muted)}.brut-foldout .agent-card dd{font:700 .66rem/1.3 monospace;text-transform:uppercase;margin:.25rem 0 0}
    .brut-foldout table{width:100%;border-collapse:collapse;font:.65rem/1.25 monospace;text-transform:uppercase}.brut-foldout th,.brut-foldout td{border:1px solid var(--line);padding:.7rem;text-align:left}.brut-foldout thead{background:var(--ink);color:var(--paper)}.brut-foldout tbody th{font-size:.78rem}.brut-foldout th small{display:block;color:var(--muted);margin-top:.25rem}
    .brut-foldout .spend-band{display:grid;grid-template-columns:repeat(4,1fr);border:2px solid var(--line);font:.64rem monospace;text-transform:uppercase}.brut-foldout .spend-band span{padding:.75rem;border-right:1px solid var(--line)}.brut-foldout .spend-band span:last-child{border:0}.brut-foldout .truth-grid{display:grid;grid-template-columns:repeat(3,1fr);margin-top:1rem}.brut-foldout .truth-card{border:2px solid var(--line);border-right:0;padding:.8rem}.brut-foldout .truth-card:last-child{border-right:2px solid var(--line)}.brut-foldout .truth-card>span{font:.6rem monospace}.brut-foldout .truth-card h3{font-size:clamp(2rem,4vw,4rem);text-transform:uppercase;margin:3rem 0 .5rem}.brut-foldout .truth-card strong,.brut-foldout .truth-card p{font:.65rem/1.35 monospace;text-transform:uppercase}.brut-foldout .truth-card:last-child{background:var(--accent);color:#fff}
    .brut-foldout .wizard{display:grid;grid-template-columns:1fr 2fr;border:2px solid var(--line)}.brut-foldout .create-steps{list-style:none;margin:0;padding:0;border-right:2px solid var(--line)}.brut-foldout .create-steps li{display:grid;grid-template-columns:3rem 1fr;min-height:3.2rem;border-bottom:1px solid var(--line);align-items:center;font:.64rem monospace;text-transform:uppercase}.brut-foldout .create-steps li:first-child{background:var(--accent);color:#fff}.brut-foldout .create-steps .step-no{height:100%;display:grid;place-items:center;border-right:1px solid currentColor}.brut-foldout .create-steps strong{padding:.5rem}.brut-foldout .goal{padding:1rem}.brut-foldout .goal h3{font-size:2.2rem;text-transform:uppercase;margin:0 0 2rem}.brut-foldout .goal dl>div{display:grid;grid-template-columns:8rem 1fr;border-top:1px solid var(--line);padding:.75rem 0}.brut-foldout .goal dt{font:.57rem monospace;text-transform:uppercase;color:var(--muted)}.brut-foldout .goal dd{font:700 .73rem/1.5 monospace;margin:0}.brut-foldout .interlock{border:5px solid var(--accent);padding:.7rem;font:.67rem/1.4 monospace;text-transform:uppercase;margin-top:1rem}
    @media(max-width:900px){.brut-foldout .roster-strip,.brut-foldout .fold{grid-template-columns:1fr}.brut-foldout .roster-card{border-right:0;border-bottom:1px solid var(--line)}.brut-foldout .diagram{border-right:0;border-bottom:2px solid var(--line)}.brut-foldout .agent-grid,.brut-foldout .truth-grid{grid-template-columns:1fr}.brut-foldout .agent-card,.brut-foldout .truth-card{border-right:0;border-bottom:1px solid var(--line)}.brut-foldout .truth-card:last-child{border-right:0}.brut-foldout .wizard{grid-template-columns:1fr}.brut-foldout .create-steps{border-right:0;border-bottom:2px solid var(--line)}}
    @media(max-width:620px){.brut-foldout{padding:0}.brut-foldout .sheet{border-left:0;border-right:0}.brut-foldout .folio{grid-template-columns:1fr}.brut-foldout .folio-title{display:block}.brut-foldout .folio-title h1{font-size:3.3rem}.brut-foldout .folio-title p{margin-top:1rem}.brut-foldout .theme{border-left:0;border-top:1px solid var(--line);padding:.5rem}.brut-foldout .theme:before{display:inline;margin-right:.5rem}.brut-foldout .tabs button{display:grid;text-align:center;padding:.55rem .2rem;font-size:.52rem}.brut-foldout .tabs button span{margin-bottom:.25rem}.brut-foldout .roster-card{grid-template-columns:2.4rem 1fr}.brut-foldout .roster-card dl{grid-column:1/-1;border-left:0;border-top:1px solid var(--line)}.brut-foldout .topology{grid-template-columns:1fr 1fr}.brut-foldout .topology li:nth-child(2){border-right:2px solid var(--line)}.brut-foldout .overlay-line{grid-template-columns:1fr 1fr}.brut-foldout .telemetry-grid{grid-template-columns:1fr}.brut-foldout .readout{border-right:0}.brut-foldout .spend-band{grid-template-columns:1fr 1fr}.brut-foldout .spend-band span:nth-child(2){border-right:0}.brut-foldout table{display:block;overflow:auto}.brut-foldout .goal dl>div{grid-template-columns:1fr;gap:.45rem}}
    @media(prefers-reduced-motion:reduce){.brut-foldout *{scroll-behavior:auto!important}}
  </style>
  <div class="sheet">
    <header class="folio"><div class="folio-title"><h1>Work<br>flows</h1><p>Bitterblossom® / Configuration manual<br>Workflow is the primary product object<br>${esc(corpus.notice)}</p></div><button type="button" class="theme" data-theme-toggle>Change substrate</button></header>
    <nav class="tabs" aria-label="Primary">${viewButtons("§")}</nav>
    <main>
      <section data-panel="workflows">
        <p class="notice">Plate 01 / configured roster — select a workflow, then inspect its stable topology with an instance overlay.</p>
        <div class="roster-strip">${workflowRows(corpus,"roster-card")}</div>
        <div class="fold"><div class="diagram"><div class="section-label"><span>Plate 02 / topology</span><span>${esc(corpus.run.id)}</span></div><h2>${esc(selected.name)}</h2><ol class="topology">${topology(selected,corpus.run)}</ol><div class="overlay-line"><span>Trigger<br><strong>${esc(corpus.run.trigger)}</strong></span><span>Parent<br><strong>${esc(corpus.run.parent)}</strong></span><span>Current step<br><strong>${esc(corpus.run.step)}</strong></span><span>Elapsed<br><strong>${esc(corpus.run.elapsed)}</strong></span></div></div><aside class="telemetry"><header><span>Selected overlay</span><span>Live</span></header><dl class="telemetry-grid"><div class="readout"><dt>Workflow lifecycle</dt><dd>${esc(selected.lifecycle)}</dd><p>Configuration state.</p></div><div class="readout"><dt>Trigger</dt><dd>Listening</dd><p>${esc(selected.trigger)}</p></div><div class="readout"><dt>Run lifecycle</dt><dd>${esc(corpus.run.state)}</dd><p>Current instance.</p></div><div class="readout"><dt>Latest execution</dt><dd>${esc(selected.latestExecution)}</dd><p>Completed process state.</p></div><div class="readout"><dt>Domain result</dt><dd>${esc(selected.latestDomain)}</dd><p>Succeeded execution can still find a blocker.</p></div><div class="readout"><dt>Verification</dt><dd>${esc(selected.verification)}</dd><p>Evidence state.</p></div><div class="readout"><dt>Cost</dt><dd>${esc(corpus.run.cost)}</dd><p>Coverage gap, never $0.</p></div><div class="readout"><dt>Budget</dt><dd>${esc(corpus.run.budget)}</dd><p>${esc(selected.budget)}</p></div></dl></aside></div>
      </section>
      <section class="panel" data-panel="agents" hidden><header class="panel-title"><span>02</span><h2>Agent register</h2></header><p class="panel-intro">In use identifies agents commissioned by configured workflows. Available identifies live Roster definitions not currently commissioned by an active workflow.</p><div class="agent-grid">${agentRows(corpus,"agent-card")}</div></section>
      <section class="panel" data-panel="runs" hidden><header class="panel-title"><span>03</span><h2>Run archive</h2></header><p class="panel-intro">A mechanical ledger of live and historical instance evidence. Superseded is not failed; blocked is a domain result, not an execution state.</p><table><thead><tr><th>No.</th><th>Workflow / reference</th><th>Execution</th><th>Domain</th><th>Verification</th><th>Cost</th></tr></thead><tbody>${runRows(corpus)}</tbody></table></section>
      <section class="panel" data-panel="spend" hidden><header class="panel-title"><span>04</span><h2>Spend control</h2></header><p class="panel-intro">Four nested admission scopes. Reporting truth remains separate from the configured ceiling.</p><div class="spend-band">${corpus.spend.scopes.map(scope=>`<span>${esc(scope)}</span>`).join("")}</div><div class="truth-grid">${spendTruth(corpus,"truth-card")}</div></section>
      <section class="panel" data-panel="create" hidden><header class="panel-title"><span>05</span><h2>New workflow</h2></header><p class="panel-intro">The manual begins with intent. Configuration follows only after the enhanced goal is reviewed as the operating contract.</p><div class="wizard"><ol class="create-steps">${steps(corpus.creation.steps)}</ol><div class="goal"><h3>Goal enhancement / operator review</h3><dl><div><dt>Raw goal</dt><dd>${esc(corpus.creation.rawGoal)}</dd></div><div><dt>Enhanced goal</dt><dd>${esc(corpus.creation.enhancedGoal)}</dd></div></dl><div class="interlock"><strong>Activation test / locked</strong><br>${esc(corpus.creation.test)}. Workflow remains Draft until the test evidence is inspected.</div></div></div></section>
    </main>
  </div>
</div>`;
}

function renderOrthographic(corpus) {
  const selected = corpus.workflows[0];
  return `
<div class="brut brut-ortho">
  <style>
    .brut-ortho{--bg:#111210;--fg:#ecece5;--muted:#aaa99e;--line:#ecece5;--red:#ff3030;--bay:#22231f;min-height:100vh;background:var(--bg);color:var(--fg);font-family:"Courier New",Courier,monospace;display:grid;grid-template-columns:minmax(0,1fr) 10rem;grid-template-rows:auto 1fr auto}
    :root[data-theme="light"] .brut-ortho{--bg:#ecebe3;--fg:#10110f;--muted:#5b5c55;--line:#10110f;--red:#d71919;--bay:#d7d6cc}
    .brut-ortho *{box-sizing:border-box}.brut-ortho button{font:inherit;color:inherit}.brut-ortho button:focus-visible{outline:4px solid var(--red);outline-offset:-4px}.brut-ortho [hidden]{display:none!important}
    .brut-ortho .statusbar{grid-column:1/-1;display:grid;grid-template-columns:auto 1fr auto;border-bottom:1px solid var(--line);min-height:3.2rem;text-transform:uppercase}.brut-ortho .brand{padding:.6rem 1rem;background:var(--red);color:#fff;font:bold 1rem/1 monospace;display:grid;place-items:center}.brut-ortho .marquee{display:flex;align-items:center;justify-content:space-between;padding:.45rem .8rem;gap:1rem;font:bold .62rem/1.2 monospace;letter-spacing:.07em}.brut-ortho .marquee span:last-child{color:var(--muted)}.brut-ortho .theme{border:0;border-left:1px solid var(--line);padding:0 1rem;background:transparent;text-transform:uppercase;font:bold .6rem monospace;cursor:pointer}
    .brut-ortho .command{grid-column:2;grid-row:2/4;border-left:1px solid var(--line);display:flex;flex-direction:column;background:var(--bay)}.brut-ortho .command-label{padding:.55rem;border-bottom:1px solid var(--line);font:bold .55rem/1.3 monospace;text-transform:uppercase;letter-spacing:.08em;color:var(--muted)}.brut-ortho .command nav{display:grid}.brut-ortho .command nav button{min-height:4.4rem;border:0;border-bottom:1px solid var(--line);background:transparent;text-align:left;padding:.55rem;text-transform:uppercase;font:bold .65rem/1.15 monospace;cursor:pointer;display:grid;align-content:space-between}.brut-ortho .command nav button span{font-size:.5rem;color:var(--muted)}.brut-ortho .command nav button[aria-current]{background:var(--fg);color:var(--bg)}.brut-ortho .command nav button[aria-current] span{color:var(--bg)}.brut-ortho .command .legend{margin-top:auto;padding:.65rem;font:.53rem/1.5 monospace;text-transform:uppercase;color:var(--muted)}
    .brut-ortho main{grid-column:1;grid-row:2;min-width:0}.brut-ortho [data-panel]{min-height:calc(100vh - 6.6rem)}
    .brut-ortho .workflow-panel{display:grid;grid-template-rows:auto 1fr}.brut-ortho .roster{display:grid;grid-template-columns:repeat(2,1fr);border-bottom:1px solid var(--line)}.brut-ortho .roster-card{display:grid;grid-template-columns:3.4rem minmax(9rem,.75fr) 1fr;border-right:1px solid var(--line);min-height:8.2rem}.brut-ortho .roster-card:last-child{border:0}.brut-ortho .roster-card .serial{border-right:1px solid var(--line);padding:.45rem;writing-mode:vertical-rl;font-size:.55rem}.brut-ortho .roster-card h3{font-family:Arial,Helvetica,sans-serif;font-size:clamp(1.4rem,2.9vw,3.6rem);line-height:.85;letter-spacing:-.055em;text-transform:uppercase;margin:.55rem;align-self:end}.brut-ortho .roster-card dl{margin:0;border-left:1px solid var(--line);display:grid;grid-template-columns:1fr 1fr}.brut-ortho .roster-card dl>div{padding:.35rem;border-right:1px solid var(--line);border-bottom:1px solid var(--line)}.brut-ortho .roster-card dt{font-size:.48rem;text-transform:uppercase;color:var(--muted)}.brut-ortho .roster-card dd{margin:.2rem 0 0;font-size:.56rem;font-weight:bold;text-transform:uppercase}.brut-ortho .roster-card:first-child{box-shadow:inset 0 .42rem var(--red)}
    .brut-ortho .table-map{display:grid;grid-template-columns:10rem minmax(0,1fr) 15rem;min-height:0}.brut-ortho .axis{border-right:1px solid var(--line);display:grid;grid-template-rows:auto repeat(4,1fr)}.brut-ortho .axis h2{margin:0;padding:.55rem;border-bottom:1px solid var(--line);font:bold .56rem monospace;text-transform:uppercase;color:var(--muted)}.brut-ortho .axis div{padding:.55rem;border-bottom:1px solid var(--line);font:.58rem/1.3 monospace;text-transform:uppercase;display:flex;flex-direction:column;justify-content:space-between}.brut-ortho .axis div:last-child{border:0}.brut-ortho .axis strong{font-size:.8rem;color:var(--red)}
    .brut-ortho .canvas{position:relative;display:grid;grid-template-rows:auto 1fr auto;overflow:hidden}.brut-ortho .canvas-head{padding:.7rem;border-bottom:1px solid var(--line);display:flex;justify-content:space-between;gap:1rem}.brut-ortho .canvas-head h1{margin:0;font-family:Arial,Helvetica,sans-serif;font-size:clamp(2.8rem,6.7vw,8rem);line-height:.72;letter-spacing:-.075em;text-transform:uppercase}.brut-ortho .canvas-head output{align-self:start;border:1px solid var(--red);color:var(--red);padding:.45rem;font:bold .58rem monospace;text-transform:uppercase}.brut-ortho .topology{list-style:none;margin:0;padding:2rem 1rem;display:grid;grid-template-columns:repeat(4,1fr);align-items:center}.brut-ortho .topology li{border:1px solid var(--line);border-right:0;min-height:9rem;padding:.55rem;display:grid;grid-template-rows:auto 1fr auto;position:relative}.brut-ortho .topology li:last-child{border-right:1px solid var(--line)}.brut-ortho .topology li:after{content:"+";position:absolute;right:-.38rem;top:-.65rem;background:var(--bg);padding:.1rem;color:var(--red)}.brut-ortho .topology li:last-child:after{display:none}.brut-ortho .topology strong{align-self:center;font-family:Arial,Helvetica,sans-serif;font-size:clamp(.8rem,1.6vw,1.5rem);text-transform:uppercase}.brut-ortho .topology small,.brut-ortho .node-index{font-size:.53rem;text-transform:uppercase;color:var(--muted)}.brut-ortho .topology [data-state="executing"]{background:var(--red);color:#fff;border-color:var(--red)}.brut-ortho .topology [data-state="executing"] small{color:#fff}.brut-ortho .children{display:grid;grid-template-columns:repeat(3,1fr);border-top:1px solid var(--line)}.brut-ortho .child{padding:.55rem;border-right:1px solid var(--line);font:.56rem/1.3 monospace;text-transform:uppercase}.brut-ortho .child:last-child{border:0}.brut-ortho .child strong,.brut-ortho .child span,.brut-ortho .child small{display:block}.brut-ortho .child span{color:var(--red);margin:.35rem 0}.brut-ortho .child small{color:var(--muted)}
    .brut-ortho .probe{border-left:1px solid var(--line);display:flex;flex-direction:column}.brut-ortho .probe header{background:var(--fg);color:var(--bg);padding:.55rem;font:bold .56rem monospace;text-transform:uppercase}.brut-ortho .readout{padding:.65rem;border-bottom:1px solid var(--line)}.brut-ortho .readout dt{font:.52rem monospace;text-transform:uppercase;color:var(--muted)}.brut-ortho .readout dd{margin:.6rem 0 0;font:bold .82rem/1.1 monospace;text-transform:uppercase}.brut-ortho .readout p{font:.52rem/1.35 monospace;text-transform:uppercase;color:var(--muted);margin:.45rem 0 0}
    .brut-ortho .lower{grid-column:1;grid-row:3;border-top:1px solid var(--line);min-height:3.4rem;display:grid;grid-template-columns:10rem 1fr auto;font:.56rem/1.2 monospace;text-transform:uppercase}.brut-ortho .lower>span{padding:.55rem;border-right:1px solid var(--line);display:flex;align-items:center}.brut-ortho .lower>span:last-child{border:0;color:var(--red)}
    .brut-ortho .panel{padding:.75rem}.brut-ortho .panel-head{display:grid;grid-template-columns:auto 1fr;border-bottom:1px solid var(--line);padding-bottom:.7rem}.brut-ortho .panel-head span{font:bold 4rem/.7 monospace;color:var(--red);padding-right:1rem}.brut-ortho .panel-head h2{font-family:Arial,Helvetica,sans-serif;font-size:clamp(3rem,8vw,9rem);line-height:.7;letter-spacing:-.075em;text-transform:uppercase;margin:0}.brut-ortho .panel-head p{grid-column:2;font:.62rem/1.35 monospace;text-transform:uppercase;max-width:65ch}
    .brut-ortho .agent-grid,.brut-ortho .truth-grid{display:grid;grid-template-columns:repeat(3,1fr);margin-top:1rem;border:1px solid var(--line)}.brut-ortho .agent-card,.brut-ortho .truth-card{padding:.65rem;border-right:1px solid var(--line)}.brut-ortho .agent-card:last-child,.brut-ortho .truth-card:last-child{border:0}.brut-ortho .agent-card header{display:flex;justify-content:space-between;font-size:.53rem;text-transform:uppercase}.brut-ortho .agent-card header strong{color:var(--red)}.brut-ortho .agent-card h3{font-family:Arial,Helvetica,sans-serif;font-size:clamp(1.8rem,4vw,4.7rem);line-height:.8;letter-spacing:-.055em;text-transform:uppercase;margin:4rem 0 .8rem}.brut-ortho .agent-card dl>div{border-top:1px solid var(--line);padding:.4rem 0}.brut-ortho .agent-card dt{font-size:.5rem;text-transform:uppercase;color:var(--muted)}.brut-ortho .agent-card dd{font-size:.58rem;font-weight:bold;text-transform:uppercase;margin:.2rem 0 0}
    .brut-ortho table{width:100%;border-collapse:collapse;margin-top:1rem;font:.6rem/1.25 monospace;text-transform:uppercase}.brut-ortho th,.brut-ortho td{border:1px solid var(--line);padding:.65rem;text-align:left}.brut-ortho thead{background:var(--fg);color:var(--bg)}.brut-ortho tbody th{font-size:.7rem}.brut-ortho th small{display:block;color:var(--muted);margin-top:.25rem}.brut-ortho .scope-grid{display:grid;grid-template-columns:repeat(4,1fr);margin-top:1rem;border:1px solid var(--line)}.brut-ortho .scope-grid span{padding:.7rem;border-right:1px solid var(--line);font-size:.58rem;text-transform:uppercase}.brut-ortho .scope-grid span:last-child{border:0}.brut-ortho .truth-card h3{font-family:Arial,Helvetica,sans-serif;font-size:2rem;text-transform:uppercase;margin:3rem 0 .5rem}.brut-ortho .truth-card strong,.brut-ortho .truth-card p{font-size:.58rem;line-height:1.4;text-transform:uppercase}.brut-ortho .truth-card:last-child{box-shadow:inset 0 .45rem var(--red)}
    .brut-ortho .builder{display:grid;grid-template-columns:12rem 1fr;margin-top:1rem;border:1px solid var(--line)}.brut-ortho .create-steps{list-style:none;margin:0;padding:0;border-right:1px solid var(--line)}.brut-ortho .create-steps li{display:grid;grid-template-columns:2.8rem 1fr;min-height:3rem;border-bottom:1px solid var(--line);align-items:center;font-size:.56rem;text-transform:uppercase}.brut-ortho .create-steps li:first-child{background:var(--red);color:#fff}.brut-ortho .step-no{display:grid;place-items:center;height:100%;border-right:1px solid currentColor}.brut-ortho .create-steps strong{padding:.4rem}.brut-ortho .goal{padding:.75rem}.brut-ortho .goal h3{font-family:Arial,Helvetica,sans-serif;font-size:2rem;text-transform:uppercase;margin:0 0 1rem}.brut-ortho .goal-row{display:grid;grid-template-columns:8rem 1fr;border-top:1px solid var(--line);padding:.65rem 0}.brut-ortho .goal-row span{font-size:.5rem;text-transform:uppercase;color:var(--muted)}.brut-ortho .goal-row p{font-size:.65rem;line-height:1.5;font-weight:bold;margin:0}.brut-ortho .interlock{border:1px solid var(--red);box-shadow:inset .45rem 0 var(--red);padding:.7rem;margin-top:.7rem;font-size:.58rem;line-height:1.4;text-transform:uppercase}
    @media(max-width:980px){.brut-ortho{grid-template-columns:minmax(0,1fr) 8rem}.brut-ortho .roster{grid-template-columns:1fr}.brut-ortho .roster-card{border-right:0;border-bottom:1px solid var(--line)}.brut-ortho .table-map{grid-template-columns:7rem 1fr}.brut-ortho .probe{grid-column:1/-1;border-left:0;border-top:1px solid var(--line);display:grid;grid-template-columns:repeat(4,1fr)}.brut-ortho .probe header{grid-column:1/-1}.brut-ortho .readout{border-right:1px solid var(--line)}.brut-ortho .agent-grid,.brut-ortho .truth-grid{grid-template-columns:1fr}.brut-ortho .agent-card,.brut-ortho .truth-card{border-right:0;border-bottom:1px solid var(--line)}}
    @media(max-width:660px){.brut-ortho{display:block}.brut-ortho .statusbar{display:grid;grid-template-columns:auto 1fr}.brut-ortho .marquee span:last-child{display:none}.brut-ortho .theme{grid-column:1/-1;border-left:0;border-top:1px solid var(--line);padding:.55rem}.brut-ortho .command{border-left:0;border-bottom:1px solid var(--line)}.brut-ortho .command-label,.brut-ortho .legend{display:none}.brut-ortho .command nav{grid-template-columns:repeat(5,1fr)}.brut-ortho .command nav button{min-height:3.4rem;padding:.35rem;font-size:.5rem}.brut-ortho [data-panel]{min-height:0}.brut-ortho .roster-card{grid-template-columns:2.3rem 1fr}.brut-ortho .roster-card dl{grid-column:1/-1;border-left:0;border-top:1px solid var(--line)}.brut-ortho .table-map{grid-template-columns:1fr}.brut-ortho .axis{display:none}.brut-ortho .topology{grid-template-columns:1fr 1fr;padding:.75rem}.brut-ortho .topology li:nth-child(2){border-right:1px solid var(--line)}.brut-ortho .children{grid-template-columns:1fr}.brut-ortho .child{border-right:0;border-bottom:1px solid var(--line)}.brut-ortho .probe{grid-template-columns:1fr 1fr}.brut-ortho .lower{display:none}.brut-ortho .builder{grid-template-columns:1fr}.brut-ortho .create-steps{border-right:0;border-bottom:1px solid var(--line)}.brut-ortho .scope-grid{grid-template-columns:1fr 1fr}.brut-ortho table{display:block;overflow:auto}.brut-ortho .panel-head{grid-template-columns:1fr}.brut-ortho .panel-head p{grid-column:1}.brut-ortho .goal-row{grid-template-columns:1fr;gap:.45rem}}
    @media(prefers-reduced-motion:reduce){.brut-ortho *{scroll-behavior:auto!important}}
  </style>
  <header class="statusbar"><div class="brand">BB // 03</div><div class="marquee"><span>[ Workflow command table ]</span><span>${esc(corpus.notice)}</span></div><button class="theme" type="button" data-theme-toggle>Substrate / invert</button></header>
  <aside class="command"><div class="command-label">View selector<br>Keyboard reachable</div><nav aria-label="Primary">${viewButtons("V")}</nav><p class="legend">State key<br><br>[RED] current execution<br>[STRIKE] complete step<br>[OPEN] pending step<br><br>Configuration state and run evidence occupy separate bays.</p></aside>
  <main>
    <section class="workflow-panel" data-panel="workflows">
      <div class="roster">${workflowRows(corpus,"roster-card")}</div>
      <div class="table-map"><aside class="axis"><h2>Coordinate / truth channel</h2><div><span>Y-01</span><strong>${esc(selected.lifecycle)}</strong><span>Workflow configuration</span></div><div><span>Y-02</span><strong>Listening</strong><span>Trigger health</span></div><div><span>Y-03</span><strong>${esc(corpus.run.state)}</strong><span>Run lifecycle</span></div><div><span>Y-04</span><strong>${esc(selected.latestDomain)}</strong><span>Domain result</span></div></aside><div class="canvas"><header class="canvas-head"><h1>${esc(selected.name)}</h1><output>Overlay / ${esc(corpus.run.id)}</output></header><ol class="topology">${topology(selected,corpus.run)}</ol><div class="children">${corpus.run.children.map(child=>`<article class="child"><strong>${esc(child.name)}</strong><span>${esc(child.state)}</span><small>${esc(child.result)}</small></article>`).join("")}</div></div><aside class="probe"><header>Selected instance probe</header><dl class="readout"><dt>Trigger event</dt><dd>${esc(corpus.run.trigger)}</dd><p>${esc(selected.trigger)}</p></dl><dl class="readout"><dt>Current step</dt><dd>${esc(corpus.run.step)}</dd><p>Elapsed ${esc(corpus.run.elapsed)}</p></dl><dl class="readout"><dt>Verification</dt><dd>${esc(selected.verification)}</dd><p>Distinct from execution and result.</p></dl><dl class="readout"><dt>Cost truth</dt><dd>${esc(corpus.run.cost)}</dd><p>${esc(corpus.run.budget)}; unknown is not zero.</p></dl></aside></div>
    </section>
    <section class="panel" data-panel="agents" hidden><header class="panel-head"><span>A</span><h2>Roster agents</h2><p>Defined identities are visible whether already commissioned by a workflow or available for configuration.</p></header><div class="agent-grid">${agentRows(corpus,"agent-card")}</div></section>
    <section class="panel" data-panel="runs" hidden><header class="panel-head"><span>R</span><h2>Evidence ledger</h2><p>History keeps superseded instances and no-run workflows visible. No evidence state is silently converted into success or failure.</p></header><table><thead><tr><th>Index</th><th>Workflow / reference</th><th>Execution</th><th>Domain</th><th>Verification</th><th>Cost</th></tr></thead><tbody>${runRows(corpus)}</tbody></table></section>
    <section class="panel" data-panel="spend" hidden><header class="panel-head"><span>$</span><h2>Admission + reporting</h2><p>Controls define whether work may begin. Reporting declares whether a value came from a receipt, a pinned estimate, or nowhere yet.</p></header><div class="scope-grid">${corpus.spend.scopes.map(scope=>`<span>${esc(scope)}</span>`).join("")}</div><div class="truth-grid">${spendTruth(corpus,"truth-card")}</div></section>
    <section class="panel" data-panel="create" hidden><header class="panel-head"><span>+</span><h2>Commission workflow</h2><p>The control table inverts form-first setup: operational intent is reviewed before the trigger, agent, environment, authority, or spend controls are admitted.</p></header><div class="builder"><ol class="create-steps">${steps(corpus.creation.steps)}</ol><div class="goal"><h3>Goal / enhanced contract</h3><div class="goal-row"><span>Input</span><p>${esc(corpus.creation.rawGoal)}</p></div><div class="goal-row"><span>Review version</span><p>${esc(corpus.creation.enhancedGoal)}</p></div><div class="interlock"><strong>Activation test required</strong><br>${esc(corpus.creation.test)}. The configuration remains Draft until the test is run and its evidence reviewed.</div></div></div></section>
  </main>
  <footer class="lower"><span>Plane / ready</span><span>${esc(selected.trigger)}</span><span>No active run / ${esc(corpus.workflows[1].name)}</span></footer>
</div>`;
}

export const SPECS = {
  "BRUT-1": {
    id: "BRUT-1",
    label: "Redline control ledger",
    move: "Persistent ledger rail, three-column workflow inspection, and evidence register make plural state mechanically scannable.",
    philosophy: "Swiss industrial control ledger: oversized type, redline exceptions, visible compartments, and no ornamental surface.",
    render: renderLedger
  },
  "BRUT-2": {
    id: "BRUT-2",
    label: "Foldout operations manual",
    move: "A full-width configured roster unfolds into a horizontal topology plate and a separate telemetry specification column.",
    philosophy: "Swiss machinery manual: folio-scale headings, numbered plates, dense specification blocks, and paper-first hierarchy.",
    render: renderFoldout
  },
  "BRUT-3": {
    id: "BRUT-3",
    label: "Orthographic command table",
    move: "Inverts dashboard navigation into a right-edge command strip while the stable workflow graph becomes the load-bearing coordinate plane.",
    philosophy: "Tactical orthographic telemetry: dark mechanical bays, monospaced probes, crosshair topology, and red reserved for the live execution seam.",
    render: renderOrthographic
  }
};
