const escapeHtml = value => String(value ?? "")
  .replaceAll("&", "&amp;")
  .replaceAll("<", "&lt;")
  .replaceAll(">", "&gt;")
  .replaceAll('"', "&quot;")
  .replaceAll("'", "&#039;");

const e = escapeHtml;

function viewButton(view, label, current = false) {
  return `<button type="button" data-view="${view}"${current ? ' aria-current="true"' : ""}>${label}</button>`;
}

function workflowRows(corpus, className = "workflow-row") {
  return corpus.workflows.map((workflow, index) => `
    <button class="${className}" type="button"${index === 0 ? ' aria-current="true"' : ""}>
      <span class="wf-title"><strong>${e(workflow.name)}</strong><small>${e(workflow.lifecycle)}</small></span>
      <span class="wf-trigger">${e(workflow.trigger)}</span>
      <span class="wf-run">${workflow.active ? `${e(workflow.active)} active` : "No active run"}</span>
    </button>`).join("");
}

function agentRows(corpus) {
  return corpus.agents.map(agent => `
    <tr>
      <th scope="row"><strong>${e(agent.name)}</strong><small>${e(agent.harness)}</small></th>
      <td><span class="state state-${agent.availability === "In use" ? "live" : "quiet"}">${e(agent.availability)}</span></td>
      <td>${e(agent.model)}</td>
      <td>${e(agent.ceiling)}</td>
      <td>${e(agent.workflows)}</td>
      <td>${agent.active ? `${e(agent.active)} active` : "No active run"}</td>
    </tr>`).join("");
}

function runRows(corpus) {
  return corpus.recentRuns.map(run => `
    <tr>
      <th scope="row"><strong>${e(run.workflow)}</strong><small>${e(run.ref)}</small></th>
      <td><span class="state state-${run.execution === "Succeeded" ? "success" : run.execution === "Superseded" ? "quiet" : "empty"}">${e(run.execution)}</span></td>
      <td><span class="state state-${run.domain === "Blocked" ? "blocked" : "quiet"}">${e(run.domain)}</span></td>
      <td>${e(run.verification)}</td>
      <td>${e(run.cost)}</td>
    </tr>`).join("");
}

function spendTruth(corpus) {
  return corpus.spend.truth.map(item => `
    <div class="truth-line">
      <strong>${e(item.label)}</strong>
      <span>${e(item.value)}</span>
      <small>${e(item.state)}</small>
    </div>`).join("");
}

function createSteps(corpus) {
  return corpus.creation.steps.map((step, index) => `
    <li class="${index === 0 ? "current" : ""}"><span>${index + 1}</span>${e(step)}</li>`).join("");
}

function topology(corpus, prefix) {
  return corpus.workflows[0].topology.map((node, index, nodes) => `
    <div class="topology-node ${index === 2 ? "is-running" : index < 2 ? "is-complete" : ""}">
      <span class="node-index">${index + 1}</span>
      <strong>${e(node)}</strong>
      <small>${index === 0 ? e(corpus.run.trigger) : index === 1 ? e(corpus.run.parent) : index === 2 ? e(corpus.run.state) : "Awaiting completion"}</small>
    </div>${index < nodes.length - 1 ? `<span class="${prefix}-connector" aria-hidden="true"></span>` : ""}`).join("");
}

function im1(corpus) {
  return `
  <style>
    .impec-1{--bg:oklch(0.975 0.006 255);--panel:oklch(1 0 0);--panel-2:oklch(0.945 0.01 255);--ink:oklch(0.22 0.025 255);--muted:oklch(0.44 0.025 255);--line:oklch(0.84 0.018 255);--accent:oklch(0.53 0.18 250);--accent-soft:oklch(0.93 0.035 250);--good:oklch(0.47 0.13 154);--warn:oklch(0.55 0.15 63);--bad:oklch(0.52 0.18 28);color:var(--ink);background:var(--bg);font:13px/1.45 Inter,ui-sans-serif,system-ui,sans-serif;min-height:100vh}
    html[data-theme="dark"] .impec-1{--bg:oklch(0.16 0.02 255);--panel:oklch(0.20 0.022 255);--panel-2:oklch(0.24 0.023 255);--ink:oklch(0.93 0.01 255);--muted:oklch(0.72 0.02 255);--line:oklch(0.35 0.025 255);--accent:oklch(0.72 0.15 250);--accent-soft:oklch(0.28 0.07 250);--good:oklch(0.72 0.14 154);--warn:oklch(0.77 0.15 75);--bad:oklch(0.71 0.16 28)}
    @media(prefers-color-scheme:dark){html:not([data-theme]) .impec-1{--bg:oklch(0.16 0.02 255);--panel:oklch(0.20 0.022 255);--panel-2:oklch(0.24 0.023 255);--ink:oklch(0.93 0.01 255);--muted:oklch(0.72 0.02 255);--line:oklch(0.35 0.025 255);--accent:oklch(0.72 0.15 250);--accent-soft:oklch(0.28 0.07 250);--good:oklch(0.72 0.14 154);--warn:oklch(0.77 0.15 75);--bad:oklch(0.71 0.16 28)}}
    .impec-1 *{box-sizing:border-box}.impec-1 button,.impec-1 input,.impec-1 textarea{font:inherit}.impec-1 button{color:inherit}.impec-1 [hidden]{display:none!important}.impec-1 button:focus-visible,.impec-1 input:focus-visible,.impec-1 textarea:focus-visible{outline:2px solid var(--accent);outline-offset:2px}
    .im1-shell{display:grid;grid-template-columns:260px minmax(480px,1fr) 310px;grid-template-rows:52px calc(100vh - 52px);min-height:100vh}.im1-head{grid-column:1/-1;display:flex;align-items:center;border-bottom:1px solid var(--line);background:var(--panel);padding:0 16px;gap:20px}.im1-brand{font-weight:760;letter-spacing:-.02em}.im1-head nav{display:flex;height:100%;align-items:end;gap:4px}.im1-head nav button{border:0;background:transparent;padding:0 12px;height:100%;border-bottom:2px solid transparent;cursor:pointer}.im1-head nav button[aria-current]{border-color:var(--accent);color:var(--accent);font-weight:700}.im1-head .head-actions{margin-left:auto;display:flex;align-items:center;gap:10px}.fixture{color:var(--muted);font-size:11px}.theme{border:1px solid var(--line);background:transparent;border-radius:6px;padding:6px 9px;cursor:pointer}
    .im1-roster{border-right:1px solid var(--line);background:var(--panel-2);padding:16px 12px;overflow:auto}.section-title{font-size:11px;font-weight:750;color:var(--muted);margin:0 4px 10px}.workflow-row{width:100%;text-align:left;border:0;border-radius:8px;background:transparent;padding:11px;margin:0 0 6px;display:grid;gap:7px;cursor:pointer}.workflow-row[aria-current]{background:var(--panel);box-shadow:0 2px 7px color-mix(in oklch,var(--ink) 9%,transparent)}.wf-title{display:flex;justify-content:space-between;gap:8px}.wf-title small{color:var(--muted)}.wf-trigger{color:var(--muted);font-size:11px}.wf-run{font-size:11px;font-weight:650}.im1-roster .new{width:100%;border:1px solid var(--accent);color:var(--accent);background:transparent;border-radius:7px;padding:8px;margin-top:10px;font-weight:700}
    .im1-main{overflow:auto;background:var(--bg)}.im1-panel{min-height:100%;padding:22px}.panel-head{display:flex;align-items:flex-start;justify-content:space-between;gap:24px;margin-bottom:20px}.panel-head h1{font-size:20px;line-height:1.2;margin:0 0 5px;letter-spacing:-.025em}.panel-head p{margin:0;color:var(--muted)}.state{display:inline-flex;align-items:center;border-radius:999px;padding:3px 7px;font-size:11px;font-weight:700;white-space:nowrap}.state-live{background:var(--accent-soft);color:var(--accent)}.state-success{background:color-mix(in oklch,var(--good) 14%,transparent);color:var(--good)}.state-blocked{background:color-mix(in oklch,var(--bad) 14%,transparent);color:var(--bad)}.state-quiet,.state-empty{background:var(--panel-2);color:var(--muted)}
    .im1-topology{display:flex;align-items:center;background:var(--panel);border:1px solid var(--line);border-radius:10px;padding:22px;overflow:auto;min-height:168px}.topology-node{flex:0 0 126px;min-height:92px;border:1px solid var(--line);border-radius:8px;padding:11px;display:flex;flex-direction:column;gap:8px;background:var(--panel)}.topology-node.is-complete{border-color:color-mix(in oklch,var(--good) 55%,var(--line))}.topology-node.is-running{border:2px solid var(--accent);background:var(--accent-soft)}.topology-node small{color:var(--muted);font-size:11px}.node-index{font-size:10px;color:var(--muted)}.im1-connector{height:1px;background:var(--line);min-width:22px;flex:1}.summary-band{display:grid;grid-template-columns:repeat(4,1fr);border-bottom:1px solid var(--line);border-top:1px solid var(--line);margin-top:22px}.summary-band div{padding:14px;border-right:1px solid var(--line)}.summary-band div:last-child{border:0}.summary-band span{display:block;color:var(--muted);font-size:11px;margin-bottom:4px}.summary-band strong{font-size:12px}
    .im1-inspector{border-left:1px solid var(--line);background:var(--panel);padding:18px;overflow:auto}.im1-inspector h2{font-size:14px;margin:0 0 4px}.im1-inspector>p{color:var(--muted);margin:0 0 16px}.child{display:grid;grid-template-columns:8px 1fr;gap:9px;padding:12px 0;border-top:1px solid var(--line)}.child-dot{width:7px;height:7px;border-radius:50%;background:var(--good);margin-top:5px}.child.is-running .child-dot{background:var(--accent)}.child strong,.child small{display:block}.child small{color:var(--muted);margin-top:3px}.truth-note{margin-top:16px;padding:12px;background:var(--panel-2);border-radius:7px}.truth-note strong,.truth-note span{display:block}.truth-note span{color:var(--muted);font-size:11px;margin-top:4px}
    .data-table{width:100%;border-collapse:collapse;background:var(--panel);border:1px solid var(--line)}.data-table th,.data-table td{padding:12px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}.data-table thead th{font-size:11px;color:var(--muted);font-weight:650;background:var(--panel-2)}.data-table tbody th small{display:block;color:var(--muted);font-weight:400;margin-top:3px}.truth-grid{display:grid;grid-template-columns:repeat(3,1fr);gap:10px}.truth-line{border-top:2px solid var(--line);padding:14px 2px}.truth-line strong,.truth-line span,.truth-line small{display:block}.truth-line span{margin:8px 0}.truth-line small{color:var(--muted)}.scope-list{display:flex;flex-wrap:wrap;gap:7px;margin:18px 0}.scope-list span{border:1px solid var(--line);border-radius:999px;padding:5px 9px}
    .create-grid{display:grid;grid-template-columns:180px minmax(0,1fr);gap:24px}.create-steps{list-style:none;margin:0;padding:0}.create-steps li{display:flex;align-items:center;gap:9px;padding:8px;color:var(--muted)}.create-steps li span{display:grid;place-items:center;width:22px;height:22px;border-radius:50%;background:var(--panel-2);font-size:11px}.create-steps li.current{color:var(--ink);font-weight:700}.create-steps li.current span{background:var(--accent);color:white}.create-form{max-width:760px}.create-form label{display:block;font-weight:700;margin:0 0 7px}.create-form textarea,.create-form input{width:100%;border:1px solid var(--line);background:var(--panel);color:var(--ink);border-radius:7px;padding:11px}.create-form textarea{min-height:76px;resize:vertical}.enhanced{margin-top:15px;border-top:1px solid var(--line);padding-top:15px}.enhanced p{max-width:72ch}.activation{display:flex;align-items:center;justify-content:space-between;gap:16px;border-top:1px solid var(--line);margin-top:18px;padding-top:16px}.primary{border:0;background:var(--accent);color:white;border-radius:7px;padding:9px 13px;font-weight:750}.primary[disabled]{background:var(--panel-2);color:var(--muted)}
    @media(max-width:900px){.im1-shell{grid-template-columns:210px 1fr;grid-template-rows:52px calc(100vh - 52px)}.im1-inspector{display:none}.im1-head .fixture{display:none}.im1-head nav{overflow:auto}.summary-band{grid-template-columns:1fr 1fr}.create-grid{grid-template-columns:1fr}.create-steps{display:flex;overflow:auto}.truth-grid{grid-template-columns:1fr}}
    @media(max-width:620px){.im1-shell{display:block}.im1-head{height:auto;min-height:52px;flex-wrap:wrap;padding-block:8px}.im1-head nav{order:3;width:100%;height:38px}.im1-roster{border:0;border-bottom:1px solid var(--line);display:flex;gap:6px;overflow:auto}.im1-roster .section-title,.im1-roster .new{display:none}.workflow-row{min-width:190px}.im1-panel{padding:16px}.data-table{display:block;overflow:auto}}
    @media(prefers-reduced-motion:reduce){.impec-1 *{scroll-behavior:auto!important;transition:none!important}}
  </style>
  <div class="impec-1">
    <div class="im1-shell">
      <header class="im1-head"><div class="im1-brand">Bitterblossom</div><nav aria-label="Primary">${viewButton("overview","Workflows",true)}${viewButton("agents","Agents")}${viewButton("runs","Runs")}${viewButton("spend","Spend")}${viewButton("create","Create workflow")}</nav><div class="head-actions"><span class="fixture">${e(corpus.notice)}</span><button class="theme" type="button" data-theme-toggle aria-label="Toggle color theme">Theme</button></div></header>
      <aside class="im1-roster"><p class="section-title">Configured workflows</p>${workflowRows(corpus)}<button class="new" type="button" data-view="create">+ Create workflow</button></aside>
      <main class="im1-main">
        <section class="im1-panel" data-panel="overview"><div class="panel-head"><div><h1>PR Review</h1><p>${e(corpus.workflows[0].trigger)}</p></div><span class="state state-live">${e(corpus.workflows[0].lifecycle)} · Trigger listening</span></div><div class="im1-topology" aria-label="PR Review configured topology">${topology(corpus,"im1")}</div><div class="summary-band"><div><span>Selected run</span><strong>${e(corpus.run.id)}</strong></div><div><span>Lifecycle</span><strong>${e(corpus.run.state)} · ${e(corpus.run.step)}</strong></div><div><span>Authority</span><strong>${e(corpus.run.budget)}</strong></div><div><span>Cost</span><strong>${e(corpus.run.cost)}</strong></div></div></section>
        <section class="im1-panel" data-panel="agents" hidden><div class="panel-head"><div><h1>Roster agents</h1><p>Pinned identities, authority ceilings, and current use.</p></div></div><table class="data-table"><thead><tr><th>Agent</th><th>Availability</th><th>Model</th><th>Authority ceiling</th><th>Workflows</th><th>Live work</th></tr></thead><tbody>${agentRows(corpus)}</tbody></table></section>
        <section class="im1-panel" data-panel="runs" hidden><div class="panel-head"><div><h1>Run evidence</h1><p>Execution, domain result, and verification remain separate.</p></div></div><table class="data-table"><thead><tr><th>Run</th><th>Execution</th><th>Domain result</th><th>Verification</th><th>Cost</th></tr></thead><tbody>${runRows(corpus)}</tbody></table></section>
        <section class="im1-panel" data-panel="spend" hidden><div class="panel-head"><div><h1>Spend controls</h1><p>Admission and reporting truth are shown without false precision.</p></div></div><div class="scope-list">${corpus.spend.scopes.map(scope=>`<span>${e(scope)}</span>`).join("")}</div><div class="truth-grid">${spendTruth(corpus)}</div></section>
        <section class="im1-panel" data-panel="create" hidden><div class="panel-head"><div><h1>Create workflow</h1><p>Start with the outcome; bind mechanism and authority after review.</p></div></div><div class="create-grid"><ol class="create-steps">${createSteps(corpus)}</ol><div class="create-form"><label for="im1-goal">What should this workflow accomplish?</label><textarea id="im1-goal">${e(corpus.creation.rawGoal)}</textarea><div class="enhanced"><strong>Enhanced goal review</strong><p>${e(corpus.creation.enhancedGoal)}</p><button class="theme" type="button">Use enhanced goal</button></div><div class="activation"><span><strong>Activation test</strong><br><small>${e(corpus.creation.test)}</small></span><button class="primary" type="button" disabled>Activate workflow</button></div></div></div></section>
      </main>
      <aside class="im1-inspector"><h2>Live overlay</h2><p>${e(corpus.run.id)} · ${e(corpus.run.elapsed)}</p>${corpus.run.children.map(child=>`<div class="child ${child.state === "Executing" ? "is-running" : ""}"><span class="child-dot"></span><div><strong>${e(child.name)}</strong><small>${e(child.state)} · ${e(child.result)}</small></div></div>`).join("")}<div class="truth-note"><strong>Verification: ${e(corpus.workflows[0].verification)}</strong><span>Latest completed execution succeeded with a blocked domain result.</span></div></aside>
    </div>
  </div>`;
}

function im2(corpus) {
  return `
  <style>
    .impec-2{--bg:oklch(0.985 0 0);--ink:oklch(0.18 0.012 285);--muted:oklch(0.43 0.014 285);--line:oklch(0.83 0.012 285);--wash:oklch(0.955 0.009 285);--accent:oklch(0.49 0.17 305);--accent-wash:oklch(0.93 0.035 305);--good:oklch(0.45 0.12 150);--bad:oklch(0.49 0.18 25);min-height:100vh;background:var(--bg);color:var(--ink);font:14px/1.5 ui-sans-serif,system-ui,sans-serif}.impec-2 *{box-sizing:border-box}.impec-2 button,.impec-2 textarea{font:inherit;color:inherit}.impec-2 [hidden]{display:none!important}
    html[data-theme="dark"] .impec-2{--bg:oklch(0.145 0.012 285);--ink:oklch(0.93 0.008 285);--muted:oklch(0.71 0.015 285);--line:oklch(0.34 0.014 285);--wash:oklch(0.205 0.014 285);--accent:oklch(0.73 0.15 305);--accent-wash:oklch(0.26 0.06 305);--good:oklch(0.7 0.13 150);--bad:oklch(0.7 0.16 25)}
    @media(prefers-color-scheme:dark){html:not([data-theme]) .impec-2{--bg:oklch(0.145 0.012 285);--ink:oklch(0.93 0.008 285);--muted:oklch(0.71 0.015 285);--line:oklch(0.34 0.014 285);--wash:oklch(0.205 0.014 285);--accent:oklch(0.73 0.15 305);--accent-wash:oklch(0.26 0.06 305);--good:oklch(0.7 0.13 150);--bad:oklch(0.7 0.16 25)}}
    .impec-2 button:focus-visible,.impec-2 textarea:focus-visible{outline:2px solid var(--accent);outline-offset:3px}.im2-shell{min-height:100vh}.im2-mast{position:sticky;top:0;z-index:3;background:var(--bg);border-bottom:1px solid var(--line)}.im2-top{height:54px;display:flex;align-items:center;gap:20px;padding:0 28px}.im2-wordmark{font-weight:800;letter-spacing:-.025em}.im2-top .notice{color:var(--muted);font-size:11px}.im2-top .actions{margin-left:auto;display:flex;align-items:center;gap:9px}.im2-top button{border:1px solid var(--line);background:transparent;border-radius:6px;padding:6px 10px}.im2-index{display:flex;align-items:stretch;overflow:auto;padding:0 28px}.im2-index .workflow-tab{min-width:260px;border:0;border-top:3px solid transparent;background:transparent;padding:12px 18px 14px;text-align:left;display:grid;grid-template-columns:1fr auto;gap:4px 18px}.im2-index .workflow-tab[aria-current]{border-color:var(--accent);background:var(--wash)}.im2-index strong{font-size:14px}.im2-index small{color:var(--muted)}.im2-index .wf-run{grid-column:2;grid-row:1/3;align-self:center}.im2-index .new-workflow{border:0;background:transparent;color:var(--accent);font-weight:750;padding:0 20px;white-space:nowrap}
    .im2-book{display:grid;grid-template-columns:170px minmax(0,1fr);max-width:1320px;margin:0 auto}.im2-chapters{position:sticky;top:133px;height:calc(100vh - 133px);padding:28px 18px;border-right:1px solid var(--line)}.im2-chapters button{width:100%;border:0;background:transparent;text-align:left;padding:8px 9px;border-radius:5px;color:var(--muted)}.im2-chapters button[aria-current]{background:var(--accent-wash);color:var(--accent);font-weight:750}.im2-page{padding:42px 48px 80px;min-width:0}.im2-kicker{color:var(--muted);margin:0 0 7px}.im2-page h1{font-size:30px;line-height:1.15;letter-spacing:-.035em;margin:0;text-wrap:balance}.im2-page .lede{color:var(--muted);max-width:65ch;margin:12px 0 34px}.im2-rule{border:0;border-top:1px solid var(--line);margin:32px 0}.im2-statusline{display:flex;align-items:center;gap:8px;margin-top:15px}.state{display:inline-flex;border-radius:999px;padding:3px 8px;font-size:11px;font-weight:750}.state-live{background:var(--accent-wash);color:var(--accent)}.state-success{background:color-mix(in oklch,var(--good) 14%,transparent);color:var(--good)}.state-blocked{background:color-mix(in oklch,var(--bad) 15%,transparent);color:var(--bad)}.state-quiet,.state-empty{background:var(--wash);color:var(--muted)}
    .im2-flow{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.im2-flow .topology-node{padding:18px 16px;min-height:142px;border-right:1px solid var(--line);display:flex;flex-direction:column;gap:13px}.im2-flow .topology-node:last-of-type{border:0}.im2-flow .topology-node.is-running{background:var(--accent-wash)}.im2-flow .node-index{font-size:11px;color:var(--muted)}.im2-flow small{color:var(--muted)}.im2-connector{display:none}.im2-ledger{margin-top:32px}.im2-ledger h2,.im2-page h2{font-size:16px;margin:0 0 14px}.im2-child{display:grid;grid-template-columns:100px minmax(140px,1fr) 1fr;gap:16px;padding:11px 0;border-top:1px solid var(--line)}.im2-child span,.im2-child small{color:var(--muted)}
    .data-table{width:100%;border-collapse:collapse}.data-table th,.data-table td{padding:13px 10px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}.data-table thead th{color:var(--muted);font-size:11px}.data-table tbody th small{display:block;color:var(--muted);font-weight:400}.im2-truth{display:grid;grid-template-columns:1.2fr 1fr 1fr;border-top:1px solid var(--line);border-bottom:1px solid var(--line)}.truth-line{padding:18px;border-right:1px solid var(--line)}.truth-line:last-child{border:0}.truth-line>*{display:block}.truth-line span{margin:8px 0}.truth-line small{color:var(--muted)}.scope-list{display:flex;gap:8px;flex-wrap:wrap;margin:0 0 26px}.scope-list span{background:var(--wash);border-radius:4px;padding:6px 9px}
    .im2-create{display:grid;grid-template-columns:150px minmax(0,680px);gap:34px}.create-steps{list-style:none;margin:0;padding:0}.create-steps li{color:var(--muted);padding:7px 0;display:flex;gap:9px}.create-steps li span{font-variant-numeric:tabular-nums}.create-steps li.current{color:var(--accent);font-weight:750}.im2-create label{font-size:16px;font-weight:750;display:block;margin-bottom:9px}.im2-create textarea{width:100%;min-height:90px;background:var(--bg);border:1px solid var(--line);border-radius:6px;padding:12px}.enhanced{background:var(--wash);padding:18px;margin-top:20px}.enhanced p{max-width:70ch}.activation{display:flex;justify-content:space-between;align-items:center;gap:20px;border-top:1px solid var(--line);padding-top:18px;margin-top:22px}.activation button{border:0;background:var(--wash);color:var(--muted);border-radius:6px;padding:9px 13px;font-weight:750}
    @media(max-width:760px){.im2-book{display:block}.im2-chapters{position:sticky;top:133px;height:auto;z-index:2;display:flex;overflow:auto;border-right:0;border-bottom:1px solid var(--line);padding:8px;background:var(--bg)}.im2-chapters button{width:auto;white-space:nowrap}.im2-page{padding:28px 20px 60px}.im2-flow{grid-template-columns:1fr 1fr}.im2-flow .topology-node:nth-child(2){border-right:0}.im2-flow .topology-node{border-bottom:1px solid var(--line)}.im2-truth,.im2-create{grid-template-columns:1fr}.im2-create .create-steps{display:flex;overflow:auto;gap:16px}.truth-line{border-right:0;border-bottom:1px solid var(--line)}.im2-child{grid-template-columns:90px 1fr}.im2-child small{grid-column:2}.im2-top .notice{display:none}}
    @media(prefers-reduced-motion:reduce){.impec-2 *{scroll-behavior:auto!important;transition:none!important}}
  </style>
  <div class="impec-2"><div class="im2-shell">
    <header class="im2-mast"><div class="im2-top"><div class="im2-wordmark">Bitterblossom / Workflow index</div><span class="notice">${e(corpus.notice)}</span><div class="actions"><button type="button" data-theme-toggle>Theme</button></div></div><div class="im2-index" aria-label="Configured workflow index">${corpus.workflows.map((workflow,index)=>`<button class="workflow-tab" type="button"${index===0?' aria-current="true"':""}><strong>${e(workflow.name)}</strong><small>${e(workflow.lifecycle)} · ${e(workflow.trigger)}</small><span class="wf-run">${workflow.active?`${workflow.active} active`:"No active run"}</span></button>`).join("")}<button class="new-workflow" type="button" data-view="create">+ Create workflow</button></div></header>
    <div class="im2-book"><nav class="im2-chapters" aria-label="Workflow dossier">${viewButton("overview","Dossier",true)}${viewButton("agents","Agents")}${viewButton("runs","Run history")}${viewButton("spend","Spend policy")}${viewButton("create","Create")}</nav><main class="im2-page">
      <section data-panel="overview"><p class="im2-kicker">Configured workflow · ${e(corpus.workflows[0].lifecycle)}</p><h1>PR Review</h1><p class="lede">${e(corpus.workflows[0].trigger)}</p><div class="im2-statusline"><span class="state state-live">Trigger listening</span><span class="state state-live">${e(corpus.run.state)} · ${e(corpus.run.step)}</span><span>${e(corpus.run.elapsed)}</span></div><hr class="im2-rule"><h2>Stable topology with selected run overlay</h2><div class="im2-flow">${topology(corpus,"im2")}</div><div class="im2-ledger"><h2>Selected run evidence · ${e(corpus.run.id)}</h2>${corpus.run.children.map(child=>`<div class="im2-child"><span>${e(child.state)}</span><strong>${e(child.name)}</strong><small>${e(child.result)}</small></div>`).join("")}<div class="im2-statusline"><span class="state state-success">Execution succeeded</span><span class="state state-blocked">Domain result blocked</span><span class="state state-success">Verification achieved</span><span>Cost ${e(corpus.run.cost)}</span></div></div></section>
      <section data-panel="agents" hidden><p class="im2-kicker">Roster definitions</p><h1>Agents available to workflows</h1><p class="lede">In-use agents remain distinct from identities that are merely available.</p><table class="data-table"><thead><tr><th>Agent</th><th>Availability</th><th>Model</th><th>Authority ceiling</th><th>Workflows</th><th>Live work</th></tr></thead><tbody>${agentRows(corpus)}</tbody></table></section>
      <section data-panel="runs" hidden><p class="im2-kicker">Evidence ledger</p><h1>Live and historical runs</h1><p class="lede">Lifecycle, domain outcome, verification, and cost are independent fields.</p><table class="data-table"><thead><tr><th>Run</th><th>Execution</th><th>Domain result</th><th>Verification</th><th>Cost</th></tr></thead><tbody>${runRows(corpus)}</tbody></table></section>
      <section data-panel="spend" hidden><p class="im2-kicker">Admission and reporting</p><h1>Spend policy</h1><p class="lede">Unknown cost remains unavailable, never silently zero.</p><div class="scope-list">${corpus.spend.scopes.map(scope=>`<span>${e(scope)}</span>`).join("")}</div><div class="im2-truth">${spendTruth(corpus)}</div></section>
      <section data-panel="create" hidden><p class="im2-kicker">Goal-first setup</p><h1>Create workflow</h1><p class="lede">Review the enhanced goal before choosing trigger, agent, authority, and limits.</p><div class="im2-create"><ol class="create-steps">${createSteps(corpus)}</ol><div><label for="im2-goal">Goal</label><textarea id="im2-goal">${e(corpus.creation.rawGoal)}</textarea><div class="enhanced"><strong>Enhanced goal review</strong><p>${e(corpus.creation.enhancedGoal)}</p></div><div class="activation"><span><strong>Activation test</strong><br><small>${e(corpus.creation.test)}</small></span><button type="button" disabled>Activate workflow</button></div></div></div></section>
    </main></div>
  </div></div>`;
}

function im3(corpus) {
  return `
  <style>
    .impec-3{--bg:oklch(0.17 0.018 200);--surface:oklch(0.205 0.02 200);--surface-2:oklch(0.245 0.021 200);--ink:oklch(0.93 0.012 200);--muted:oklch(0.70 0.025 200);--line:oklch(0.35 0.025 200);--accent:oklch(0.77 0.14 188);--accent-soft:oklch(0.27 0.055 188);--good:oklch(0.75 0.13 145);--bad:oklch(0.72 0.17 25);min-height:100vh;background:var(--bg);color:var(--ink);font:13px/1.42 ui-sans-serif,system-ui,sans-serif}.impec-3 *{box-sizing:border-box}.impec-3 button,.impec-3 textarea{font:inherit;color:inherit}.impec-3 [hidden]{display:none!important}
    html[data-theme="light"] .impec-3{--bg:oklch(0.97 0.007 200);--surface:oklch(0.995 0.002 200);--surface-2:oklch(0.93 0.012 200);--ink:oklch(0.20 0.022 200);--muted:oklch(0.43 0.03 200);--line:oklch(0.82 0.025 200);--accent:oklch(0.47 0.13 188);--accent-soft:oklch(0.90 0.045 188);--good:oklch(0.43 0.12 145);--bad:oklch(0.52 0.18 25)}
    @media(prefers-color-scheme:light){html:not([data-theme]) .impec-3{--bg:oklch(0.97 0.007 200);--surface:oklch(0.995 0.002 200);--surface-2:oklch(0.93 0.012 200);--ink:oklch(0.20 0.022 200);--muted:oklch(0.43 0.03 200);--line:oklch(0.82 0.025 200);--accent:oklch(0.47 0.13 188);--accent-soft:oklch(0.90 0.045 188);--good:oklch(0.43 0.12 145);--bad:oklch(0.52 0.18 25)}}
    .impec-3 button:focus-visible,.impec-3 textarea:focus-visible{outline:2px solid var(--accent);outline-offset:2px}.im3-shell{display:grid;grid-template-rows:50px 1fr 46px;min-height:100vh}.im3-head{display:flex;align-items:center;padding:0 16px;border-bottom:1px solid var(--line);background:var(--surface);gap:14px}.im3-logo{font-weight:800;letter-spacing:-.02em}.im3-head .crumb{color:var(--muted)}.im3-head .notice{margin-left:auto;color:var(--muted);font-size:11px}.im3-head button{border:1px solid var(--line);background:transparent;border-radius:5px;padding:6px 9px}.im3-stage{min-height:0;position:relative}.im3-overview{height:calc(100vh - 96px);display:grid;grid-template-columns:220px minmax(420px,1fr) 280px;min-height:560px}.im3-column{min-height:0;overflow:auto}.im3-workflows{border-right:1px solid var(--line);background:var(--surface);padding:14px 10px}.im3-workflows h2,.im3-evidence h2{font-size:12px;margin:4px 6px 12px;color:var(--muted)}.workflow-row{width:100%;border:0;background:transparent;border-radius:6px;padding:10px;text-align:left;display:grid;gap:6px;margin-bottom:5px}.workflow-row[aria-current]{background:var(--accent-soft)}.wf-title{display:flex;justify-content:space-between;gap:8px}.wf-title small,.wf-trigger{color:var(--muted);font-size:11px}.wf-run{font-size:11px}.im3-workflows .create{width:100%;border:1px solid var(--line);background:transparent;border-radius:5px;padding:8px;margin-top:8px;color:var(--accent);font-weight:750}
    .im3-canvas{position:relative;overflow:auto;padding:22px;background:var(--bg)}.im3-canvas-head{display:flex;align-items:flex-start;justify-content:space-between;gap:16px}.im3-canvas h1{font-size:18px;letter-spacing:-.02em;margin:0 0 4px}.im3-canvas p{margin:0;color:var(--muted)}.im3-chipset{display:flex;gap:6px;flex-wrap:wrap;justify-content:flex-end}.state{display:inline-flex;border-radius:999px;padding:3px 7px;font-size:10px;font-weight:750}.state-live{background:var(--accent-soft);color:var(--accent)}.state-success{background:color-mix(in oklch,var(--good) 15%,transparent);color:var(--good)}.state-blocked{background:color-mix(in oklch,var(--bad) 15%,transparent);color:var(--bad)}.state-quiet,.state-empty{background:var(--surface-2);color:var(--muted)}
    .im3-graph{position:relative;margin-top:22px;min-height:390px;border:1px solid var(--line);background:var(--surface);overflow:auto}.im3-graph:before{content:"Configured topology";position:absolute;top:12px;left:14px;color:var(--muted);font-size:11px}.im3-graph .graph-track{display:flex;align-items:center;min-width:650px;position:absolute;inset:58px 34px 76px}.im3-graph .topology-node{position:relative;flex:0 0 132px;min-height:94px;border:1px solid var(--line);background:var(--surface);padding:11px;border-radius:6px;display:flex;flex-direction:column;gap:8px}.im3-graph .topology-node.is-complete{border-color:var(--good)}.im3-graph .topology-node.is-running{border:2px solid var(--accent);background:var(--accent-soft)}.im3-graph .topology-node small,.im3-graph .node-index{color:var(--muted);font-size:10px}.im3-connector{height:1px;background:var(--line);flex:1;min-width:30px}.run-tape{position:absolute;left:14px;right:14px;bottom:13px;display:grid;grid-template-columns:1.3fr repeat(3,1fr);border-top:1px solid var(--line);padding-top:12px}.run-tape div{padding:0 10px;border-right:1px solid var(--line)}.run-tape div:last-child{border:0}.run-tape span,.run-tape strong{display:block}.run-tape span{font-size:10px;color:var(--muted);margin-bottom:3px}.run-tape strong{font-size:11px}
    .im3-evidence{border-left:1px solid var(--line);background:var(--surface);padding:14px 14px 24px}.evidence-row{padding:12px 5px;border-top:1px solid var(--line)}.evidence-row span,.evidence-row strong,.evidence-row small{display:block}.evidence-row span{color:var(--muted);font-size:10px}.evidence-row strong{margin:4px 0}.evidence-row small{color:var(--muted)}.evidence-summary{margin-top:14px;background:var(--accent-soft);padding:12px;border-radius:6px}.evidence-summary strong,.evidence-summary span{display:block}.evidence-summary span{color:var(--muted);font-size:11px;margin-top:5px}
    .im3-dock{display:flex;align-items:center;justify-content:center;gap:4px;border-top:1px solid var(--line);background:var(--surface);padding:5px;overflow:auto}.im3-dock button{border:0;background:transparent;border-radius:5px;padding:7px 12px;color:var(--muted);white-space:nowrap}.im3-dock button[aria-current]{background:var(--accent-soft);color:var(--accent);font-weight:750}.im3-panel{height:calc(100vh - 96px);overflow:auto;padding:24px}.im3-panel-head{display:flex;align-items:flex-start;justify-content:space-between;margin-bottom:22px}.im3-panel h1{font-size:20px;margin:0 0 4px}.im3-panel p{margin:0;color:var(--muted)}
    .data-table{width:100%;border-collapse:collapse;background:var(--surface)}.data-table th,.data-table td{padding:12px;text-align:left;border-bottom:1px solid var(--line);vertical-align:top}.data-table thead th{font-size:10px;color:var(--muted)}.data-table tbody th small{display:block;color:var(--muted);font-weight:400;margin-top:3px}.im3-spend{display:grid;grid-template-columns:220px 1fr;gap:28px}.scope-list{display:flex;flex-direction:column;gap:7px}.scope-list span{border-bottom:1px solid var(--line);padding:8px}.truth-line{display:grid;grid-template-columns:100px 1fr 1fr;gap:14px;padding:14px 0;border-top:1px solid var(--line)}.truth-line small{color:var(--muted)}
    .im3-create{display:grid;grid-template-columns:minmax(160px,220px) minmax(0,720px);gap:34px}.create-steps{list-style:none;margin:0;padding:0}.create-steps li{display:flex;gap:9px;color:var(--muted);padding:8px}.create-steps li span{color:var(--muted)}.create-steps li.current{background:var(--accent-soft);color:var(--accent);border-radius:5px;font-weight:750}.im3-create label{display:block;font-weight:750;font-size:15px;margin-bottom:8px}.im3-create textarea{width:100%;min-height:82px;color:var(--ink);background:var(--surface);border:1px solid var(--line);border-radius:6px;padding:11px}.enhanced{margin-top:18px;border:1px solid var(--line);padding:16px}.enhanced p{max-width:70ch;margin:8px 0}.activation{display:flex;justify-content:space-between;align-items:center;gap:16px;padding-top:16px;margin-top:18px;border-top:1px solid var(--line)}.activation button{border:0;background:var(--surface-2);color:var(--muted);border-radius:5px;padding:8px 12px;font-weight:750}
    @media(max-width:860px){.im3-overview{grid-template-columns:190px 1fr}.im3-evidence{display:none}.im3-spend,.im3-create{grid-template-columns:1fr}.scope-list{flex-direction:row;flex-wrap:wrap}.truth-line{grid-template-columns:90px 1fr}.truth-line small{grid-column:2}.im3-head .notice{display:none}}
    @media(max-width:600px){.im3-overview{display:block;height:calc(100vh - 96px);overflow:auto}.im3-workflows{display:flex;gap:6px;overflow:auto;border-right:0;border-bottom:1px solid var(--line)}.im3-workflows h2,.im3-workflows .create{display:none}.workflow-row{min-width:190px}.im3-canvas{overflow:visible}.im3-panel{padding:16px}.data-table{display:block;overflow:auto}}
    @media(prefers-reduced-motion:reduce){.impec-3 *{scroll-behavior:auto!important;transition:none!important}}
  </style>
  <div class="impec-3"><div class="im3-shell">
    <header class="im3-head"><div class="im3-logo">Bitterblossom</div><span class="crumb">/ PR Review / live overlay</span><span class="notice">${e(corpus.notice)}</span><button type="button" data-theme-toggle>Theme</button></header>
    <main class="im3-stage">
      <section class="im3-overview" data-panel="overview"><aside class="im3-workflows im3-column"><h2>Configured workflows</h2>${workflowRows(corpus)}<button class="create" type="button" data-view="create">+ Create workflow</button></aside><div class="im3-canvas im3-column"><div class="im3-canvas-head"><div><h1>PR Review</h1><p>${e(corpus.workflows[0].trigger)}</p></div><div class="im3-chipset"><span class="state state-live">Active</span><span class="state state-live">Trigger listening</span><span class="state state-live">${e(corpus.run.state)}</span></div></div><div class="im3-graph"><div class="graph-track">${topology(corpus,"im3")}</div><div class="run-tape"><div><span>Selected overlay</span><strong>${e(corpus.run.id)}</strong></div><div><span>Current step</span><strong>${e(corpus.run.step)} · ${e(corpus.run.elapsed)}</strong></div><div><span>Budget</span><strong>${e(corpus.run.budget)}</strong></div><div><span>Cost</span><strong>${e(corpus.run.cost)}</strong></div></div></div></div><aside class="im3-evidence im3-column"><h2>Evidence drawer</h2>${corpus.run.children.map(child=>`<div class="evidence-row"><span>${e(child.state)}</span><strong>${e(child.name)}</strong><small>${e(child.result)}</small></div>`).join("")}<div class="evidence-summary"><strong>Verification achieved</strong><span>Succeeded execution · blocked domain result</span></div></aside></section>
      <section class="im3-panel" data-panel="agents" hidden><div class="im3-panel-head"><div><h1>Agents</h1><p>In-use and available Roster definitions.</p></div></div><table class="data-table"><thead><tr><th>Agent</th><th>Availability</th><th>Model</th><th>Authority ceiling</th><th>Workflows</th><th>Live work</th></tr></thead><tbody>${agentRows(corpus)}</tbody></table></section>
      <section class="im3-panel" data-panel="runs" hidden><div class="im3-panel-head"><div><h1>Runs</h1><p>Live and history evidence without collapsing distinct states.</p></div></div><table class="data-table"><thead><tr><th>Run</th><th>Execution</th><th>Domain result</th><th>Verification</th><th>Cost</th></tr></thead><tbody>${runRows(corpus)}</tbody></table></section>
      <section class="im3-panel" data-panel="spend" hidden><div class="im3-panel-head"><div><h1>Spend</h1><p>Controls and reporting coverage.</p></div></div><div class="im3-spend"><div class="scope-list">${corpus.spend.scopes.map(scope=>`<span>${e(scope)}</span>`).join("")}</div><div>${spendTruth(corpus)}</div></div></section>
      <section class="im3-panel" data-panel="create" hidden><div class="im3-panel-head"><div><h1>Create workflow</h1><p>Goal first; authority and activation remain explicit gates.</p></div></div><div class="im3-create"><ol class="create-steps">${createSteps(corpus)}</ol><div><label for="im3-goal">What should the workflow accomplish?</label><textarea id="im3-goal">${e(corpus.creation.rawGoal)}</textarea><div class="enhanced"><strong>Enhanced goal review</strong><p>${e(corpus.creation.enhancedGoal)}</p></div><div class="activation"><span><strong>Activation test</strong><br><small>${e(corpus.creation.test)}</small></span><button type="button" disabled>Activate workflow</button></div></div></div></section>
    </main>
    <nav class="im3-dock" aria-label="Primary">${viewButton("overview","Workflow canvas",true)}${viewButton("agents","Agents")}${viewButton("runs","Runs")}${viewButton("spend","Spend")}${viewButton("create","Create workflow")}</nav>
  </div></div>`;
}

export const SPECS = {
  "IMPEC-1": {
    id: "IMPEC-1",
    label: "Three-pane control room",
    move: "Pins workflow roster, configured topology, and live evidence into simultaneous scan lanes.",
    philosophy: "Earned familiarity, state separation, and dense progressive disclosure with a restrained product vocabulary.",
    render: im1
  },
  "IMPEC-2": {
    id: "IMPEC-2",
    label: "Workflow dossier",
    move: "Inverts the app-shell assumption: workflows are a persistent horizontal index and the selected workflow reads as one operational dossier.",
    philosophy: "A task-first document model with typographic hierarchy, stable controls, and no decorative card scaffolding.",
    render: im2
  },
  "IMPEC-3": {
    id: "IMPEC-3",
    label: "Graph-first evidence workbench",
    move: "Makes the stable workflow graph the central work surface, flanked by roster selection and a live evidence drawer.",
    philosophy: "Operational density centered on the product's true object, using motionless state overlays and explicit evidence truth.",
    render: im3
  }
};
