#!/usr/bin/env bash
set -euo pipefail

usage() {
	cat <<'EOF'
Usage: ./scripts/onboard.sh [options]

Generate shell exports for Bitterblossom local usage.

Options:
  --app <slug>        Set FLY_APP explicitly
  --org <slug>        Set FLY_ORG explicitly (default: infer from sprite org)
  --token <token>     Set FLY_API_TOKEN explicitly
  --write <path>      Write exports to file (e.g. .env.bb)
  --print             Print exports to stdout (default)
  -h, --help          Show help

Notes:
  - If no Fly token is found, a placeholder is emitted.
  - Create a token with:
      fly tokens create org -o <org> -n bb-cli -x 720h
EOF
}

need_cmd() {
	local name="$1"
	if ! command -v "$name" >/dev/null 2>&1; then
		echo "error: missing required command: $name" >&2
		exit 1
	fi
}

infer_org() {
	if [[ -n "${FLY_ORG:-}" ]]; then
		printf '%s\n' "$FLY_ORG"
		return
	fi
	if command -v sprite >/dev/null 2>&1; then
		local line
		line="$(sprite org list 2>/dev/null | sed -n 's/^Currently selected org: //p' | head -n1 || true)"
		if [[ -n "$line" ]]; then
			printf '%s\n' "$line"
			return
		fi
	fi
	printf '%s\n' "misty-step"
}

infer_app() {
	local org="$1"
	if [[ -n "${FLY_APP:-}" ]]; then
		printf '%s\n' "$FLY_APP"
		return
	fi
	if ! command -v fly >/dev/null 2>&1 || ! command -v jq >/dev/null 2>&1; then
		printf '%s\n' ""
		return
	fi

	local apps_json
	apps_json="$(fly apps list --json 2>/dev/null || true)"
	if [[ -z "$apps_json" ]]; then
		printf '%s\n' ""
		return
	fi

	local app
	app="$(printf '%s\n' "$apps_json" | jq -r --arg org "$org" '
		map(select(.Organization.Slug == $org)) |
		(map(select(.Name | test("bitterblossom"))) | .[0].Name) // empty
	' || true)"
	if [[ -n "$app" ]]; then
		printf '%s\n' "$app"
		return
	fi

	app="$(printf '%s\n' "$apps_json" | jq -r --arg org "$org" '
		map(select(.Organization.Slug == $org)) |
		if length == 1 then .[0].Name else "" end
	' || true)"
	printf '%s\n' "$app"
}

infer_fly_token() {
	if [[ -n "${FLY_API_TOKEN:-}" ]]; then
		printf '%s\n' "$FLY_API_TOKEN"
		return
	fi
	if [[ -n "${FLY_TOKEN:-}" ]]; then
		printf '%s\n' "$FLY_TOKEN"
		return
	fi
	printf '%s\n' ""
}

infer_gh_token() {
	if [[ -n "${SPRITE_GITHUB_DEFAULT_TOKEN:-}" ]]; then
		printf '%s\n' "$SPRITE_GITHUB_DEFAULT_TOKEN"
		return
	fi
	if command -v gh >/dev/null 2>&1; then
		gh auth token 2>/dev/null || true
		return
	fi
	printf '%s\n' ""
}

shell_quote() {
	printf '%q' "$1"
}

main() {
	local app=""
	local org=""
	local token=""
	local out_file=""
	local print_mode=true

	while [[ $# -gt 0 ]]; do
		case "$1" in
			--app)
				app="${2:-}"
				shift 2
				;;
			--org)
				org="${2:-}"
				shift 2
				;;
			--token)
				token="${2:-}"
				shift 2
				;;
			--write)
				out_file="${2:-}"
				shift 2
				;;
			--print)
				print_mode=true
				shift
				;;
			-h|--help)
				usage
				exit 0
				;;
			*)
				echo "error: unknown arg: $1" >&2
				usage >&2
				exit 1
				;;
		esac
	done

	need_cmd bash
	need_cmd fly
	need_cmd sprite
	need_cmd gh

	if [[ -z "$org" ]]; then
		org="$(infer_org)"
	fi
	if [[ -z "$app" ]]; then
		app="$(infer_app "$org")"
	fi
	if [[ -z "$token" ]]; then
		token="$(infer_fly_token)"
	fi

	local gh_token
	gh_token="$(infer_gh_token)"

	local openrouter_key
	openrouter_key="${OPENROUTER_API_KEY:-}"

	local content
	content="$(
		cat <<EOF
# Generated by scripts/onboard.sh
export FLY_ORG=$(shell_quote "$org")
export FLY_APP=$(shell_quote "$app")
export FLY_API_TOKEN=$(shell_quote "$token")
export OPENROUTER_API_KEY=$(shell_quote "$openrouter_key")
export SPRITE_GITHUB_DEFAULT_USER='misty-step-sprites'
export SPRITE_GITHUB_DEFAULT_EMAIL='misty-step-sprites@users.noreply.github.com'
export SPRITE_GITHUB_DEFAULT_TOKEN=$(shell_quote "$gh_token")
EOF
	)"

	if [[ -n "$out_file" ]]; then
		printf '%s\n' "$content" > "$out_file"
		echo "wrote $out_file"
	fi

	if [[ "$print_mode" == true ]]; then
		printf '%s\n' "$content"
	fi

	if [[ -z "$app" ]]; then
		echo >&2
		echo "warning: could not infer FLY_APP. set it manually (likely: bitterblossom-dash)." >&2
	fi
	if [[ -z "$token" ]]; then
		echo >&2
		echo "warning: FLY_API_TOKEN empty. create one with:" >&2
		echo "  fly tokens create org -o $org -n bb-cli -x 720h" >&2
	fi
	if [[ -z "$openrouter_key" ]]; then
		echo >&2
		echo "warning: OPENROUTER_API_KEY empty. set it before dispatch." >&2
	fi
}

main "$@"
