export const OPTIONS=[
  {id:"BASE-1",group:"Baseline",lane:"Current",label:"Shipped Aesthetic configuration ledger",move:"Current rail, summary band, and dense configuration tables."},
  {id:"ANTH-1",group:"Candidates",lane:"Anthropic",label:"Split signal desk",move:"Roster, stable configuration, and selected-run evidence remain simultaneously scannable."},
  {id:"ANTH-2",group:"Candidates",lane:"Anthropic",label:"Inline workflow atlas",move:"Configuration and evidence expand beneath the roster row instead of opening a detail page."},
  {id:"ANTH-3",group:"Candidates",lane:"Anthropic",label:"Topology aperture",move:"The stable route becomes the working surface; runtime evidence enters through a dedicated aperture."},
  {id:"MIN-1",group:"Candidates",lane:"Minimal",label:"Index and folio",move:"A persistent workflow index opens one editorial operating dossier."},
  {id:"MIN-2",group:"Candidates",lane:"Minimal",label:"Run before workflow",move:"The selected live instance leads; configuration becomes provenance beside it."},
  {id:"MIN-3",group:"Candidates",lane:"Minimal",label:"Configuration / evidence diptych",move:"Stable configuration and selected-run evidence receive equal territory in a technical spread."},
  {id:"BRUT-1",group:"Candidates",lane:"Brutalist",label:"Control ledger",move:"A fixed destination rail fronts a ruled roster above an evidence-and-spend desk."},
  {id:"BRUT-2",group:"Candidates",lane:"Brutalist",label:"Circuit register",move:"Topology becomes navigation, with roster coordinates and evidence quadrants."},
  {id:"BRUT-3",group:"Candidates",lane:"Brutalist",label:"Procedure before inventory",move:"Goal-first creation owns the primary desk; configuration acts as its proof ledger."},
  {id:"APPLE-1",group:"Candidates",lane:"Apple",label:"Source-anchored workbench",move:"A fixed workflow source anchors a directly movable live-run overlay."},
  {id:"APPLE-2",group:"Candidates",lane:"Apple",label:"Topology-first board",move:"The topology is the stage; live, agent, and evidence lanes occupy a ruled board."},
  {id:"APPLE-3",group:"Candidates",lane:"Apple",label:"Run-first evidence spine",move:"The selected run and its evidence own the first read; configuration stays anchored as context."}
];

const nav=document.querySelector('#options'),frame=document.querySelector('#frame'),viewport=document.querySelector('#viewport'),counter=document.querySelector('#counter'),width=document.querySelector('#width'),height=document.querySelector('#height'),preset=document.querySelector('#preset'),scaleOut=document.querySelector('#scale');
const shellMode=document.querySelector('#shell-mode'),copyPage=document.querySelector('#copy-page');
let selected=localStorage.getItem('bb-lab-004-option')||'BASE-1';
function buildNav(){let group='';nav.replaceChildren();OPTIONS.forEach(o=>{if(o.group!==group){group=o.group;const h=document.createElement('div');h.className='group';h.textContent=group;nav.append(h)}const b=document.createElement('button');b.className=`option ${o.id==='BASE-1'?'baseline':''}`;b.dataset.id=o.id;b.innerHTML=`<span class="badge">${o.id} · ${o.lane}</span><strong>${o.label}</strong><small>${o.move}</small>`;b.addEventListener('click',()=>select(o.id));nav.append(b)})}
function select(id){selected=OPTIONS.some(o=>o.id===id)?id:'BASE-1';localStorage.setItem('bb-lab-004-option',selected);frame.src=`frame.html?v=1#${selected}`;document.querySelectorAll('.option').forEach(b=>b.toggleAttribute('aria-current',b.dataset.id===selected));const i=OPTIONS.findIndex(o=>o.id===selected);counter.textContent=`${i+1} / ${OPTIONS.length}`;document.querySelector(`[data-id="${selected}"]`)?.scrollIntoView({block:'nearest'})}
function fit(){const stage=document.querySelector('.stage').getBoundingClientRect(),w=Number(width.value),h=Number(height.value),s=Math.min((stage.width-32)/w,(stage.height-32)/h,1);viewport.style.width=`${w}px`;viewport.style.height=`${h}px`;viewport.style.transform=`scale(${s})`;scaleOut.value=`${Math.round(s*100)}%`}
function applyPreset(){if(preset.value==='fit'){const stage=document.querySelector('.stage').getBoundingClientRect();width.value=Math.max(320,Math.floor(stage.width-32));height.value=Math.max(480,Math.floor(stage.height-32))}else if(preset.value!=='custom'){[width.value,height.value]=preset.value.split('x')}localStorage.setItem('bb-lab-004-viewport',JSON.stringify({preset:preset.value,w:width.value,h:height.value}));fit()}
preset.addEventListener('change',applyPreset);[width,height].forEach(el=>el.addEventListener('input',()=>{preset.value='custom';fit()}));shellMode.addEventListener('click',()=>{const next=document.documentElement.classList.contains('dark')?'light':'dark';document.documentElement.classList.remove('light','dark');document.documentElement.classList.add(next);document.documentElement.style.colorScheme=next;localStorage.setItem('bb-lab-004-shell-mode',next)});copyPage.addEventListener('click',async()=>{try{const html=frame.contentDocument?.documentElement?.outerHTML||document.documentElement.outerHTML;await navigator.clipboard.writeText(`<!doctype html>\n${html}`);copyPage.textContent='Copied';setTimeout(()=>copyPage.textContent='Copy page',1200)}catch{copyPage.textContent='Copy failed';setTimeout(()=>copyPage.textContent='Copy page',1200)}});
addEventListener('resize',fit);addEventListener('keydown',e=>{if(!['ArrowDown','ArrowUp'].includes(e.key)||/INPUT|SELECT/.test(document.activeElement.tagName))return;e.preventDefault();const i=OPTIONS.findIndex(o=>o.id===selected),d=e.key==='ArrowDown'?1:-1;select(OPTIONS[(i+d+OPTIONS.length)%OPTIONS.length].id)});const saved=JSON.parse(localStorage.getItem('bb-lab-004-viewport')||'null');if(saved){preset.value=saved.preset;width.value=saved.w;height.value=saved.h}buildNav();select(selected);requestAnimationFrame(applyPreset);
